[package]
name = "ployzd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ployz-core.workspace = true
ployz-nats.workspace = true
ployz-sdk-types.workspace = true
ployz-transport.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "ployzd"
path = "src/main.rs"
