//! TypeScript generation for the transport-neutral public API contracts.

use std::collections::{BTreeMap, BTreeSet};

use ts_rs::{Config, Dependency, TS, TypeVisitor};

use super::v2::{
    API_MAJOR, ApiRefusal, ApiVersion, ContainerLensRow, CorrosionLogsTailLines,
    CorrosionNamespaceCreateRefusal, CorrosionNamespaceCreateReply,
    CorrosionNamespaceCreateRequest, CorrosionNamespaceRemoveRefusal,
    CorrosionNamespaceRemoveReply, CorrosionNamespaceRemoveRequest, CorrosionRetryAfterSeconds,
    DeployAccepted, DeployRefusal, DeployRequest, DeployServiceRequest, KNOWN_API_FEATURES,
    KnownApiFeature, LensCollection, LensSnapshot, LensWatchEvent, MachineLensRow,
    MachineRemoveRefusal, MachineRemoveReply, MachineRemoveRequest, MachineStatusLensRow,
    MachineUpgradeRefusal, MachineUpgradeReply, MachineUpgradeRequest, MachineUpgradeSupervisor,
    MachineUpgradeUrl, OperationLensRow, PinnedMachineNames, RequestedPins, RequestedPlacement,
    ServiceLensRow, ServiceLogLine, ServiceLogStream, ServiceLogsFollowEvent, ServiceLogsRefusal,
    ServiceLogsRequest, ServiceLogsTailReply,
};
use super::{
    DoctorDocument, NamedRemovalOutcome, PeerRemoveRefusal, PeerRemoveReply, PeerRemoveRequest,
    RouteAttachOutcome, RouteAttachRefusal, RouteAttachReply, RouteAttachRequest,
    RouteRemoveRefusal, RouteRemoveReply, RouteRemoveRequest, ServiceRemoveRowRefusal,
    ServiceRemoveRowReply, ServiceRemoveRowRequest, StatusDocument,
};
use crate::corrosion::{
    AcmeHttp01Document, CertHoldingDocument, ClusterDocument, ContainerDocument, CorrosionTable,
    GatewayObservationDocument, HostPortBinding, HostPortBindings, HostPortProtocol,
    MachineDocument, MachineStatusDocument, NamespaceDocument, OperationDocument, PeerDocument,
    Principal, RouteBindingDocument, ServiceDocument, TokenDocument,
};
use crate::deploy::{EnvName, EnvValue};
use crate::founding::{
    FoundingDriverEnrollment, FoundingRefusal, FoundingRepairCommand, FoundingRequest,
    FoundingResult, FoundingRow, FoundingValidationError,
};
use crate::ids::{CorrosionNamespaceName, DeployName, MachineName, RouteHostname};
use crate::join::{
    JoinAdmissionReply, JoinAdmissionRequest, JoinMachineSubstrate, MachineEndpointSetRefusal,
    MachineEndpointSetReply, MachineEndpointSetRequest, TokenCreateRefusal, TokenCreateReply,
    TokenCreateRequest, TokenListReply, TokenListRequest, TokenRevokeRefusal, TokenRevokeReply,
    TokenRevokeRequest,
};
use crate::placement::{PlacementElimination, PlacementEliminationReason, PlacementRefusal};
/// Generate the complete TypeScript API contract from the Rust domain types.
#[must_use]
pub fn api_typescript() -> String {
    let config = Config::new().with_large_int("number");
    let mut output = String::from("// Generated by ployz-core. Do not edit by hand.\n\n");

    output.push_str("export type Brand<T, B extends string> = T & { readonly __brand: B };\n\n");
    output.push_str(
        "export type SafeInteger<B extends string> = Brand<number, `safe_integer:${B}`>;\n\n",
    );
    output.push_str(&format!(
        "export const API_MAJOR = {API_MAJOR} as const;\n\n"
    ));
    output.push_str("export const KNOWN_API_FEATURES = [\n");
    for feature in KNOWN_API_FEATURES {
        output.push_str(&format!("  \"{}\",\n", feature.as_str()));
    }
    output.push_str("] as const;\n\n");
    // `ts-rs` cannot derive an untagged enum and preserve the additive
    // `KnownApiFeature | (string & {})` TypeScript widening at once.
    output.push_str("export type ApiFeature = KnownApiFeature | (string & {});\n\n");
    output.push_str("export type OperationInitiator = Principal;\n\n");

    let mut declarations = DeclarationCollector::new(&config);
    collect_corrosion_contracts(&mut declarations);
    collect_v2_contracts(&mut declarations);

    // `ServiceEnvironment` uses an explicit record representation, so ts-rs cannot discover
    // the branded key and value declarations from it.
    declarations.visit::<EnvName>();
    declarations.visit::<EnvValue>();

    declarations.write_to(&mut output);
    strip_trailing_whitespace(&output)
}

fn collect_corrosion_contracts(declarations: &mut DeclarationCollector<'_>) {
    declarations.visit::<MachineName>();
    declarations.visit::<CorrosionNamespaceName>();
    declarations.visit::<DeployName>();
    declarations.visit::<RouteHostname>();
    declarations.visit::<CorrosionTable>();
    declarations.visit::<Principal>();
    declarations.visit::<ClusterDocument>();
    declarations.visit::<MachineDocument>();
    declarations.visit::<PeerDocument>();
    declarations.visit::<TokenDocument>();
    declarations.visit::<NamespaceDocument>();
    declarations.visit::<ServiceDocument>();
    declarations.visit::<RouteBindingDocument>();
    declarations.visit::<ContainerDocument>();
    declarations.visit::<MachineStatusDocument>();
    declarations.visit::<GatewayObservationDocument>();
    declarations.visit::<OperationDocument>();
    declarations.visit::<CertHoldingDocument>();
    declarations.visit::<AcmeHttp01Document>();
}

fn collect_v2_contracts(declarations: &mut DeclarationCollector<'_>) {
    declarations.visit::<KnownApiFeature>();
    declarations.visit::<ApiVersion>();
    declarations.visit::<LensCollection>();
    declarations.visit::<MachineLensRow>();
    declarations.visit::<ServiceLensRow>();
    declarations.visit::<ContainerLensRow>();
    declarations.visit::<MachineStatusLensRow>();
    declarations.visit::<OperationLensRow>();
    declarations.visit::<LensSnapshot>();
    declarations.visit::<CorrosionRetryAfterSeconds>();
    declarations.visit::<ApiRefusal>();
    declarations.visit::<LensWatchEvent>();
    declarations.visit::<StatusDocument>();
    declarations.visit::<DoctorDocument>();
    declarations.visit::<NamedRemovalOutcome>();
    declarations.visit::<PeerRemoveRequest>();
    declarations.visit::<PeerRemoveReply>();
    declarations.visit::<PeerRemoveRefusal>();
    declarations.visit::<ServiceRemoveRowRequest>();
    declarations.visit::<ServiceRemoveRowReply>();
    declarations.visit::<ServiceRemoveRowRefusal>();
    declarations.visit::<RouteRemoveRequest>();
    declarations.visit::<RouteRemoveReply>();
    declarations.visit::<RouteRemoveRefusal>();
    declarations.visit::<RouteAttachRequest>();
    declarations.visit::<RouteAttachReply>();
    declarations.visit::<RouteAttachOutcome>();
    declarations.visit::<RouteAttachRefusal>();
    declarations.visit::<FoundingDriverEnrollment>();
    declarations.visit::<FoundingRequest>();
    declarations.visit::<FoundingRow>();
    declarations.visit::<FoundingValidationError>();
    declarations.visit::<FoundingResult>();
    declarations.visit::<FoundingRepairCommand>();
    declarations.visit::<FoundingRefusal>();
    declarations.visit::<TokenCreateRequest>();
    declarations.visit::<TokenCreateReply>();
    declarations.visit::<TokenCreateRefusal>();
    declarations.visit::<TokenListRequest>();
    declarations.visit::<TokenListReply>();
    declarations.visit::<TokenRevokeRequest>();
    declarations.visit::<TokenRevokeReply>();
    declarations.visit::<TokenRevokeRefusal>();
    declarations.visit::<MachineEndpointSetRequest>();
    declarations.visit::<MachineEndpointSetReply>();
    declarations.visit::<MachineEndpointSetRefusal>();
    declarations.visit::<MachineRemoveRequest>();
    declarations.visit::<MachineRemoveReply>();
    declarations.visit::<MachineRemoveRefusal>();
    declarations.visit::<MachineUpgradeUrl>();
    declarations.visit::<MachineUpgradeSupervisor>();
    declarations.visit::<MachineUpgradeRequest>();
    declarations.visit::<MachineUpgradeReply>();
    declarations.visit::<MachineUpgradeRefusal>();
    declarations.visit::<JoinAdmissionRequest>();
    declarations.visit::<JoinAdmissionReply>();
    declarations.visit::<JoinMachineSubstrate>();
    declarations.visit::<CorrosionNamespaceCreateRequest>();
    declarations.visit::<CorrosionNamespaceCreateReply>();
    declarations.visit::<CorrosionNamespaceCreateRefusal>();
    declarations.visit::<CorrosionNamespaceRemoveRequest>();
    declarations.visit::<CorrosionNamespaceRemoveReply>();
    declarations.visit::<CorrosionNamespaceRemoveRefusal>();
    declarations.visit::<DeployRequest>();
    declarations.visit::<DeployServiceRequest>();
    declarations.visit::<RequestedPlacement>();
    declarations.visit::<RequestedPins>();
    declarations.visit::<PinnedMachineNames>();
    declarations.visit::<HostPortProtocol>();
    declarations.visit::<HostPortBinding>();
    declarations.visit::<HostPortBindings>();
    declarations.visit::<DeployAccepted>();
    declarations.visit::<DeployRefusal>();
    declarations.visit::<PlacementElimination>();
    declarations.visit::<PlacementEliminationReason>();
    declarations.visit::<PlacementRefusal>();
    declarations.visit::<CorrosionLogsTailLines>();
    declarations.visit::<ServiceLogsRequest>();
    declarations.visit::<ServiceLogStream>();
    declarations.visit::<ServiceLogLine>();
    declarations.visit::<ServiceLogsRefusal>();
    declarations.visit::<ServiceLogsTailReply>();
    declarations.visit::<ServiceLogsFollowEvent>();
}

struct DeclarationCollector<'a> {
    config: &'a Config,
    seen: BTreeSet<String>,
    declared: BTreeSet<String>,
    declarations: BTreeMap<String, String>,
}

impl<'a> DeclarationCollector<'a> {
    fn new(config: &'a Config) -> Self {
        Self {
            config,
            seen: BTreeSet::new(),
            declared: BTreeSet::new(),
            declarations: BTreeMap::new(),
        }
    }

    fn write_to(self, output: &mut String) {
        for declaration in self.declarations.into_values() {
            output.push_str("export ");
            output.push_str(&declaration);
            output.push_str("\n\n");
        }
    }
}

impl TypeVisitor for DeclarationCollector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        let Some(dependency) = Dependency::from_ty::<T>(self.config) else {
            T::visit_dependencies(self);
            return;
        };
        if !self.seen.insert(dependency.ts_name) {
            return;
        }

        T::visit_dependencies(self);
        let name = T::name(self.config);
        self.declared.insert(name.clone());
        self.declarations.insert(name, T::decl(self.config));
    }
}

fn strip_trailing_whitespace(value: &str) -> String {
    let mut stripped = String::with_capacity(value.len());
    for line in value.lines() {
        stripped.push_str(line.trim_end());
        stripped.push('\n');
    }
    let content_len = stripped.trim_end_matches('\n').len();
    stripped.truncate(content_len);
    stripped.push('\n');
    stripped
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_declares_types_referenced_by_explicit_representations() {
        let generated = api_typescript();

        for name in ["EnvName", "EnvValue"] {
            assert!(
                generated.contains(&format!("export type {name} =")),
                "missing declaration for {name}"
            );
        }
    }

    #[test]
    fn generated_contract_declares_corrosion_documents() {
        let generated = api_typescript();

        for name in [
            "ClusterDocument",
            "MachineDocument",
            "PeerDocument",
            "TokenDocument",
            "NamespaceDocument",
            "ServiceDocument",
            "RouteBindingDocument",
            "ContainerDocument",
            "MachineStatusDocument",
            "OperationDocument",
            "CertHoldingDocument",
            "AcmeHttp01Document",
            "MachineTransport",
            "PeerTransport",
            "CorrosionTimestamp",
            "MachineName",
            "CorrosionNamespaceName",
            "DeployName",
            "RouteHostname",
        ] {
            assert!(
                generated.contains(&format!("export type {name} =")),
                "missing declaration for {name}"
            );
        }
    }

    #[test]
    fn generated_contract_declares_every_v2_public_wire_shape() {
        let generated = api_typescript();

        assert!(generated.contains("export const API_MAJOR = 1 as const;"));
        assert!(generated.contains("export const KNOWN_API_FEATURES = ["));
        assert!(generated.contains("\"v2.founding\","));
        assert!(generated.contains("\"v2.lenses\","));
        assert!(generated.contains("\"v2.namespace_primitives\","));
        assert!(generated.contains("\"v2.deploy\","));
        assert!(generated.contains("\"v2.operation_status\","));
        assert!(generated.contains("\"v2.logs\","));
        assert!(generated.contains("\"v2.machine_remove\","));
        assert!(generated.contains("\"v2.peer_remove\","));
        assert!(generated.contains("\"v2.diagnostics\","));
        assert!(generated.contains("export type ApiFeature = KnownApiFeature | (string & {});"));
        assert!(generated.contains("export type OperationInitiator = Principal;"));
        assert!(!generated.contains("export type AcceptedRosterPrincipal ="));
        assert!(!generated.contains("export type SourcePrincipalResolutionError ="));
        assert!(!generated.contains("export type MalformedRequestReason ="));
        assert!(!generated.contains("LensWatermark"));
        assert!(generated.contains("id: ContainerId, document: ContainerDocument"));

        for name in [
            "Principal",
            "KnownApiFeature",
            "ApiFeature",
            "ApiVersion",
            "LensCollection",
            "MachineLensRow",
            "ServiceLensRow",
            "ContainerLensRow",
            "MachineStatusLensRow",
            "OperationLensRow",
            "LensSnapshot",
            "CorrosionRetryAfterSeconds",
            "ApiRefusal",
            "LensWatchEvent",
            "StatusDocument",
            "DoctorDocument",
            "NamedRemovalOutcome",
            "PeerRemoveRequest",
            "PeerRemoveReply",
            "PeerRemoveRefusal",
            "ServiceRemoveRowRequest",
            "ServiceRemoveRowReply",
            "ServiceRemoveRowRefusal",
            "RouteRemoveRequest",
            "RouteRemoveReply",
            "RouteRemoveRefusal",
            "FoundingDriverEnrollment",
            "FoundingRequest",
            "FoundingRow",
            "FoundingValidationError",
            "FoundingResult",
            "FoundingRepairCommand",
            "FoundingRefusal",
            "CorrosionNamespaceCreateRequest",
            "CorrosionNamespaceCreateReply",
            "CorrosionNamespaceCreateRefusal",
            "CorrosionNamespaceRemoveRequest",
            "CorrosionNamespaceRemoveReply",
            "CorrosionNamespaceRemoveRefusal",
            "DeployRequest",
            "DeployAccepted",
            "DeployRefusal",
            "CorrosionLogsTailLines",
            "ServiceLogsRequest",
            "ServiceLogStream",
            "ServiceLogLine",
            "ServiceLogsRefusal",
            "ServiceLogsTailReply",
            "ServiceLogsFollowEvent",
            "MachineRemoveRequest",
            "MachineRemoveReply",
            "MachineRemoveRefusal",
            "PeerRemoveRequest",
            "PeerRemoveReply",
            "PeerRemoveRefusal",
        ] {
            assert!(
                generated.contains(&format!("export type {name} =")),
                "missing declaration for {name}"
            );
        }
        for local_only in [
            "InitStorageChoice",
            "InitStorageSelectionError",
            "FoundingArrival",
        ] {
            assert!(
                !generated.contains(&format!("export type {local_only} =")),
                "local-only declaration leaked: {local_only}"
            );
        }
    }
}
