linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - exhaustive
    - prealloc
    - gosec

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-dirs:
    - internal/daemon/pb
