version: 2

project_name: ployz

release:
  prerelease: auto
  extra_files:
    - glob: install.sh

before:
  hooks:
    - go mod tidy
    - sh -c "sed 's/__PLOYZ_VERSION__/{{ .Version }}/g' internal/remote/install.sh > install.sh && chmod +x install.sh"

builds:
  - id: ployz
    main: ./cmd/ployz
    binary: ployz
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X ployz/internal/buildinfo.Version={{.Version}}

  - id: ployzd
    main: ./cmd/ployzd
    binary: ployzd
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X ployz/internal/buildinfo.Version={{.Version}}

archives:
  - id: ployz-bundle
    ids: [ployz, ployzd]

homebrew_casks:
  - name: ployz
    ids: [ployz-bundle]
    directory: Casks
    repository:
      owner: getployz
      name: homebrew-ployz
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/getployz/ployz
    description: Ployz CLI and daemon
    license: MIT
    dependencies:
      - formula: wireguard-tools
      - cask: docker
    hooks:
      post:
        install: |
          if OS.mac?
            %w[ployz ployzd].each do |b|
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
            end
          end

nfpms:
  - id: ployz-linux
    package_name: ployz
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: ployz
    maintainer: ployz
    description: Ployz control plane
    license: MIT
    bindir: /usr/local/bin
    formats: [deb, rpm]
    ids: [ployz, ployzd]
    dependencies:
      - iproute2
      - iptables
      - wireguard-tools
    recommends:
      - docker-ce
    contents:
      - src: packaging/systemd/ployzd.service
        dst: /etc/systemd/system/ployzd.service
    scripts:
      postinstall: packaging/nfpm/postinstall.sh
      postremove: packaging/nfpm/postremove.sh
