version: 2

project_name: ployz

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - id: ployz
    main: ./cmd/ployz
    binary: ployz
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X ployz/internal/buildinfo.Version={{.Version}}

  - id: ployzd
    main: ./cmd/ployzd
    binary: ployzd
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X ployz/internal/buildinfo.Version={{.Version}}

  - id: ployz-runtime
    main: ./cmd/ployz-runtime
    binary: ployz-runtime
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X ployz/internal/buildinfo.Version={{.Version}}

archives:
  - id: ployz-bundle
    ids: [ployz, ployzd, ployz-runtime]

homebrew_casks:
  - name: ployz
    ids: [ployz-bundle]
    directory: Casks
    repository:
      owner: getployz
      name: homebrew-ployz
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/getployz/ployz
    description: Ployz CLI, daemon, and runtime
    license: MIT
    caveats: |
      The cask installs three binaries:
        - ployz
        - ployzd
        - ployz-runtime

      To run daemon and runtime together in user mode:
        ployz dev run
    hooks:
      post:
        install: |
          if OS.mac?
            %w[ployz ployzd ployz-runtime].each do |b|
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
            end
          end

nfpms:
  - id: ployz-linux
    package_name: ployz
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: ployz
    maintainer: ployz
    description: Ployz control plane and runtime
    license: MIT
    bindir: /usr/local/bin
    formats: [deb, rpm]
    ids: [ployz, ployzd, ployz-runtime]
    contents:
      - src: packaging/systemd/ployzd.service
        dst: /etc/systemd/system/ployzd.service
      - src: packaging/systemd/ployz-runtime.service
        dst: /etc/systemd/system/ployz-runtime.service
    scripts:
      postinstall: packaging/nfpm/postinstall.sh
      postremove: packaging/nfpm/postremove.sh
