[workspace]
members = [
    "crates/ployz-core",
    "crates/ployz-nats",
    "crates/ployz-transport",
    "crates/ployz-keeper",
    "crates/ployz-e2e",
    "crates/ployzd",
    "crates/ployzctl",
    "crates/ployz-sdk-types",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT"

[workspace.dependencies]
futures-util = "0.3"
ployz-core = { path = "crates/ployz-core" }
ployz-nats = { path = "crates/ployz-nats" }
ployz-transport = { path = "crates/ployz-transport" }
ployz-sdk-types = { path = "crates/ployz-sdk-types" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
nuid = "0.5"
tokio = "1"
ts-rs = { version = "12", features = ["no-serde-warnings"] }

[workspace.lints.clippy]
indexing_slicing = "warn"
fallible_impl_from = "warn"
wildcard_enum_match_arm = "warn"
fn_params_excessive_bools = "warn"
must_use_candidate = "warn"
