[package]
name = "ployz-ebpf-ctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap.workspace = true
ipnet = "2"
ployz-ebpf-common = { path = "../ployz-ebpf-common", features = ["validation"] }

[target.'cfg(target_os = "linux")'.dependencies]
aya = "0.13"
libc = "0.2"

[[bin]]
name = "ployz-ebpf-ctl"
path = "src/main.rs"
