[package]
name = "ployz-node-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-error = { path = "../ployz-error" }
ployz-model = { path = "../ployz-model" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
