[package]
name = "ployz-ebpf-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
validation = ["dep:object"]

[dependencies]
object = { version = "0.37.3", default-features = false, features = ["read"], optional = true }

[dev-dependencies]
object = { version = "0.37.3", default-features = false, features = ["write"] }

[lib]
path = "src/lib.rs"
