[package]
name = "ployz-host-backends"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
if-addrs = { workspace = true }
libc = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls"] }
tracing = { workspace = true }

[lints]
workspace = true
