[package]
name = "ployz-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dev-dependencies]
polis = { workspace = true, features = ["test-support"] }
ployz = { path = "../ployz", features = ["test-support"] }
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[lints]
workspace = true
