[package]
name = "ployz-runtime-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
hostname = { workspace = true }
ipnet = { workspace = true }
ployz-types = { path = "../ployz-types" }
async-trait = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "time"] }
x25519-dalek = { workspace = true }

[lints]
workspace = true
