[package]
name = "ployz-sdk-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ployz-core = { workspace = true, features = ["typescript"] }
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lib]
path = "src/lib.rs"
