// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: internal/daemon/pb/daemon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network           string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	DataRoot          string   `protobuf:"bytes,2,opt,name=data_root,json=dataRoot,proto3" json:"data_root,omitempty"`
	NetworkCidr       string   `protobuf:"bytes,3,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	Subnet            string   `protobuf:"bytes,4,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp      string   `protobuf:"bytes,5,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	AdvertiseEndpoint string   `protobuf:"bytes,6,opt,name=advertise_endpoint,json=advertiseEndpoint,proto3" json:"advertise_endpoint,omitempty"`
	WgPort            int32    `protobuf:"varint,7,opt,name=wg_port,json=wgPort,proto3" json:"wg_port,omitempty"`
	Bootstrap         []string `protobuf:"bytes,8,rep,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	HelperImage       string   `protobuf:"bytes,9,opt,name=helper_image,json=helperImage,proto3" json:"helper_image,omitempty"`
	CorrosionMemberId uint64   `protobuf:"varint,10,opt,name=corrosion_member_id,json=corrosionMemberId,proto3" json:"corrosion_member_id,omitempty"`
	CorrosionApiToken string   `protobuf:"bytes,11,opt,name=corrosion_api_token,json=corrosionApiToken,proto3" json:"corrosion_api_token,omitempty"`
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec.ProtoReflect.Descriptor instead.
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkSpec) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetworkSpec) GetDataRoot() string {
	if x != nil {
		return x.DataRoot
	}
	return ""
}

func (x *NetworkSpec) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *NetworkSpec) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *NetworkSpec) GetManagementIp() string {
	if x != nil {
		return x.ManagementIp
	}
	return ""
}

func (x *NetworkSpec) GetAdvertiseEndpoint() string {
	if x != nil {
		return x.AdvertiseEndpoint
	}
	return ""
}

func (x *NetworkSpec) GetWgPort() int32 {
	if x != nil {
		return x.WgPort
	}
	return 0
}

func (x *NetworkSpec) GetBootstrap() []string {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *NetworkSpec) GetHelperImage() string {
	if x != nil {
		return x.HelperImage
	}
	return ""
}

func (x *NetworkSpec) GetCorrosionMemberId() uint64 {
	if x != nil {
		return x.CorrosionMemberId
	}
	return 0
}

func (x *NetworkSpec) GetCorrosionApiToken() string {
	if x != nil {
		return x.CorrosionApiToken
	}
	return ""
}

type ApplyNetworkSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *NetworkSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *ApplyNetworkSpecRequest) Reset() {
	*x = ApplyNetworkSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyNetworkSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNetworkSpecRequest) ProtoMessage() {}

func (x *ApplyNetworkSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNetworkSpecRequest.ProtoReflect.Descriptor instead.
func (*ApplyNetworkSpecRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyNetworkSpecRequest) GetSpec() *NetworkSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ApplyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network             string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	NetworkCidr         string `protobuf:"bytes,2,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	Subnet              string `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp        string `protobuf:"bytes,4,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	WgInterface         string `protobuf:"bytes,5,opt,name=wg_interface,json=wgInterface,proto3" json:"wg_interface,omitempty"`
	WgPort              int32  `protobuf:"varint,6,opt,name=wg_port,json=wgPort,proto3" json:"wg_port,omitempty"`
	AdvertiseEndpoint   string `protobuf:"bytes,7,opt,name=advertise_endpoint,json=advertiseEndpoint,proto3" json:"advertise_endpoint,omitempty"`
	CorrosionName       string `protobuf:"bytes,8,opt,name=corrosion_name,json=corrosionName,proto3" json:"corrosion_name,omitempty"`
	CorrosionApiAddr    string `protobuf:"bytes,9,opt,name=corrosion_api_addr,json=corrosionApiAddr,proto3" json:"corrosion_api_addr,omitempty"`
	CorrosionGossipAddr string `protobuf:"bytes,10,opt,name=corrosion_gossip_addr,json=corrosionGossipAddr,proto3" json:"corrosion_gossip_addr,omitempty"`
	DockerNetwork       string `protobuf:"bytes,11,opt,name=docker_network,json=dockerNetwork,proto3" json:"docker_network,omitempty"`
	ConvergenceRunning  bool   `protobuf:"varint,12,opt,name=convergence_running,json=convergenceRunning,proto3" json:"convergence_running,omitempty"`
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyResult) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ApplyResult) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *ApplyResult) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *ApplyResult) GetManagementIp() string {
	if x != nil {
		return x.ManagementIp
	}
	return ""
}

func (x *ApplyResult) GetWgInterface() string {
	if x != nil {
		return x.WgInterface
	}
	return ""
}

func (x *ApplyResult) GetWgPort() int32 {
	if x != nil {
		return x.WgPort
	}
	return 0
}

func (x *ApplyResult) GetAdvertiseEndpoint() string {
	if x != nil {
		return x.AdvertiseEndpoint
	}
	return ""
}

func (x *ApplyResult) GetCorrosionName() string {
	if x != nil {
		return x.CorrosionName
	}
	return ""
}

func (x *ApplyResult) GetCorrosionApiAddr() string {
	if x != nil {
		return x.CorrosionApiAddr
	}
	return ""
}

func (x *ApplyResult) GetCorrosionGossipAddr() string {
	if x != nil {
		return x.CorrosionGossipAddr
	}
	return ""
}

func (x *ApplyResult) GetDockerNetwork() string {
	if x != nil {
		return x.DockerNetwork
	}
	return ""
}

func (x *ApplyResult) GetConvergenceRunning() bool {
	if x != nil {
		return x.ConvergenceRunning
	}
	return false
}

type DisableNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Purge   bool   `protobuf:"varint,2,opt,name=purge,proto3" json:"purge,omitempty"`
}

func (x *DisableNetworkRequest) Reset() {
	*x = DisableNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableNetworkRequest) ProtoMessage() {}

func (x *DisableNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableNetworkRequest.ProtoReflect.Descriptor instead.
func (*DisableNetworkRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DisableNetworkRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DisableNetworkRequest) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

type DisableNetworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableNetworkResponse) Reset() {
	*x = DisableNetworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableNetworkResponse) ProtoMessage() {}

func (x *DisableNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableNetworkResponse.ProtoReflect.Descriptor instead.
func (*DisableNetworkResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{4}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ClockHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NtpOffsetMs float64 `protobuf:"fixed64,1,opt,name=ntp_offset_ms,json=ntpOffsetMs,proto3" json:"ntp_offset_ms,omitempty"`
	NtpHealthy  bool    `protobuf:"varint,2,opt,name=ntp_healthy,json=ntpHealthy,proto3" json:"ntp_healthy,omitempty"`
	NtpError    string  `protobuf:"bytes,3,opt,name=ntp_error,json=ntpError,proto3" json:"ntp_error,omitempty"`
}

func (x *ClockHealth) Reset() {
	*x = ClockHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockHealth) ProtoMessage() {}

func (x *ClockHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockHealth.ProtoReflect.Descriptor instead.
func (*ClockHealth) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ClockHealth) GetNtpOffsetMs() float64 {
	if x != nil {
		return x.NtpOffsetMs
	}
	return 0
}

func (x *ClockHealth) GetNtpHealthy() bool {
	if x != nil {
		return x.NtpHealthy
	}
	return false
}

func (x *ClockHealth) GetNtpError() string {
	if x != nil {
		return x.NtpError
	}
	return ""
}

type NetworkStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Configured    bool         `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	Running       bool         `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Wireguard     bool         `protobuf:"varint,3,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	Corrosion     bool         `protobuf:"varint,4,opt,name=corrosion,proto3" json:"corrosion,omitempty"`
	Docker        bool         `protobuf:"varint,5,opt,name=docker,proto3" json:"docker,omitempty"`
	StatePath     string       `protobuf:"bytes,6,opt,name=state_path,json=statePath,proto3" json:"state_path,omitempty"`
	WorkerRunning bool         `protobuf:"varint,7,opt,name=worker_running,json=workerRunning,proto3" json:"worker_running,omitempty"`
	ClockHealth   *ClockHealth `protobuf:"bytes,8,opt,name=clock_health,json=clockHealth,proto3" json:"clock_health,omitempty"`
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatus.ProtoReflect.Descriptor instead.
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkStatus) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *NetworkStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *NetworkStatus) GetWireguard() bool {
	if x != nil {
		return x.Wireguard
	}
	return false
}

func (x *NetworkStatus) GetCorrosion() bool {
	if x != nil {
		return x.Corrosion
	}
	return false
}

func (x *NetworkStatus) GetDocker() bool {
	if x != nil {
		return x.Docker
	}
	return false
}

func (x *NetworkStatus) GetStatePath() string {
	if x != nil {
		return x.StatePath
	}
	return ""
}

func (x *NetworkStatus) GetWorkerRunning() bool {
	if x != nil {
		return x.WorkerRunning
	}
	return false
}

func (x *NetworkStatus) GetClockHealth() *ClockHealth {
	if x != nil {
		return x.ClockHealth
	}
	return nil
}

type GetIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *GetIdentityRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey           string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Subnet              string `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp        string `protobuf:"bytes,4,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	AdvertiseEndpoint   string `protobuf:"bytes,5,opt,name=advertise_endpoint,json=advertiseEndpoint,proto3" json:"advertise_endpoint,omitempty"`
	NetworkCidr         string `protobuf:"bytes,6,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	WgInterface         string `protobuf:"bytes,7,opt,name=wg_interface,json=wgInterface,proto3" json:"wg_interface,omitempty"`
	WgPort              int32  `protobuf:"varint,8,opt,name=wg_port,json=wgPort,proto3" json:"wg_port,omitempty"`
	HelperName          string `protobuf:"bytes,9,opt,name=helper_name,json=helperName,proto3" json:"helper_name,omitempty"`
	CorrosionGossipPort int32  `protobuf:"varint,10,opt,name=corrosion_gossip_port,json=corrosionGossipPort,proto3" json:"corrosion_gossip_port,omitempty"`
	Running             bool   `protobuf:"varint,11,opt,name=running,proto3" json:"running,omitempty"`
	CorrosionMemberId   uint64 `protobuf:"varint,12,opt,name=corrosion_member_id,json=corrosionMemberId,proto3" json:"corrosion_member_id,omitempty"`
	CorrosionApiToken   string `protobuf:"bytes,13,opt,name=corrosion_api_token,json=corrosionApiToken,proto3" json:"corrosion_api_token,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Identity) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *Identity) GetManagementIp() string {
	if x != nil {
		return x.ManagementIp
	}
	return ""
}

func (x *Identity) GetAdvertiseEndpoint() string {
	if x != nil {
		return x.AdvertiseEndpoint
	}
	return ""
}

func (x *Identity) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *Identity) GetWgInterface() string {
	if x != nil {
		return x.WgInterface
	}
	return ""
}

func (x *Identity) GetWgPort() int32 {
	if x != nil {
		return x.WgPort
	}
	return 0
}

func (x *Identity) GetHelperName() string {
	if x != nil {
		return x.HelperName
	}
	return ""
}

func (x *Identity) GetCorrosionGossipPort() int32 {
	if x != nil {
		return x.CorrosionGossipPort
	}
	return 0
}

func (x *Identity) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Identity) GetCorrosionMemberId() uint64 {
	if x != nil {
		return x.CorrosionMemberId
	}
	return 0
}

func (x *Identity) GetCorrosionApiToken() string {
	if x != nil {
		return x.CorrosionApiToken
	}
	return ""
}

type MachineEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey        string  `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Subnet           string  `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp     string  `protobuf:"bytes,4,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	Endpoint         string  `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastUpdated      string  `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Version          int64   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	ExpectedVersion  int64   `protobuf:"varint,8,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	FreshnessMs      float64 `protobuf:"fixed64,9,opt,name=freshness_ms,json=freshnessMs,proto3" json:"freshness_ms,omitempty"`
	Stale            bool    `protobuf:"varint,10,opt,name=stale,proto3" json:"stale,omitempty"`
	ReplicationLagMs float64 `protobuf:"fixed64,11,opt,name=replication_lag_ms,json=replicationLagMs,proto3" json:"replication_lag_ms,omitempty"`
}

func (x *MachineEntry) Reset() {
	*x = MachineEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineEntry) ProtoMessage() {}

func (x *MachineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineEntry.ProtoReflect.Descriptor instead.
func (*MachineEntry) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *MachineEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineEntry) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MachineEntry) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *MachineEntry) GetManagementIp() string {
	if x != nil {
		return x.ManagementIp
	}
	return ""
}

func (x *MachineEntry) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MachineEntry) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *MachineEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MachineEntry) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *MachineEntry) GetFreshnessMs() float64 {
	if x != nil {
		return x.FreshnessMs
	}
	return 0
}

func (x *MachineEntry) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *MachineEntry) GetReplicationLagMs() float64 {
	if x != nil {
		return x.ReplicationLagMs
	}
	return 0
}

type ListMachinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *ListMachinesRequest) Reset() {
	*x = ListMachinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMachinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesRequest) ProtoMessage() {}

func (x *ListMachinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesRequest.ProtoReflect.Descriptor instead.
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListMachinesRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ListMachinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Machines []*MachineEntry `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
}

func (x *ListMachinesResponse) Reset() {
	*x = ListMachinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesResponse) ProtoMessage() {}

func (x *ListMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesResponse.ProtoReflect.Descriptor instead.
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ListMachinesResponse) GetMachines() []*MachineEntry {
	if x != nil {
		return x.Machines
	}
	return nil
}

type UpsertMachineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string        `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Machine *MachineEntry `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
}

func (x *UpsertMachineRequest) Reset() {
	*x = UpsertMachineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMachineRequest) ProtoMessage() {}

func (x *UpsertMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMachineRequest.ProtoReflect.Descriptor instead.
func (*UpsertMachineRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertMachineRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *UpsertMachineRequest) GetMachine() *MachineEntry {
	if x != nil {
		return x.Machine
	}
	return nil
}

type UpsertMachineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpsertMachineResponse) Reset() {
	*x = UpsertMachineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMachineResponse) ProtoMessage() {}

func (x *UpsertMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMachineResponse.ProtoReflect.Descriptor instead.
func (*UpsertMachineResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{14}
}

type RemoveMachineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network      string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	IdOrEndpoint string `protobuf:"bytes,2,opt,name=id_or_endpoint,json=idOrEndpoint,proto3" json:"id_or_endpoint,omitempty"`
}

func (x *RemoveMachineRequest) Reset() {
	*x = RemoveMachineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineRequest) ProtoMessage() {}

func (x *RemoveMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineRequest.ProtoReflect.Descriptor instead.
func (*RemoveMachineRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveMachineRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *RemoveMachineRequest) GetIdOrEndpoint() string {
	if x != nil {
		return x.IdOrEndpoint
	}
	return ""
}

type RemoveMachineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveMachineResponse) Reset() {
	*x = RemoveMachineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMachineResponse) ProtoMessage() {}

func (x *RemoveMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMachineResponse.ProtoReflect.Descriptor instead.
func (*RemoveMachineResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{16}
}

type TriggerReconcileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *TriggerReconcileRequest) Reset() {
	*x = TriggerReconcileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReconcileRequest) ProtoMessage() {}

func (x *TriggerReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReconcileRequest.ProtoReflect.Descriptor instead.
func (*TriggerReconcileRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerReconcileRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type TriggerReconcileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TriggerReconcileResponse) Reset() {
	*x = TriggerReconcileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReconcileResponse) ProtoMessage() {}

func (x *TriggerReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReconcileResponse.ProtoReflect.Descriptor instead.
func (*TriggerReconcileResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{18}
}

type GetPeerHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetPeerHealthRequest) Reset() {
	*x = GetPeerHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerHealthRequest) ProtoMessage() {}

func (x *GetPeerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerHealthRequest.ProtoReflect.Descriptor instead.
func (*GetPeerHealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *GetPeerHealthRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type PeerLag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId           string  `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FreshnessMs      float64 `protobuf:"fixed64,2,opt,name=freshness_ms,json=freshnessMs,proto3" json:"freshness_ms,omitempty"`
	Stale            bool    `protobuf:"varint,3,opt,name=stale,proto3" json:"stale,omitempty"`
	ReplicationLagMs float64 `protobuf:"fixed64,4,opt,name=replication_lag_ms,json=replicationLagMs,proto3" json:"replication_lag_ms,omitempty"`
	PingMs           float64 `protobuf:"fixed64,5,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"` // TCP connect RTT in ms, -1 = unreachable
}

func (x *PeerLag) Reset() {
	*x = PeerLag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerLag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerLag) ProtoMessage() {}

func (x *PeerLag) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerLag.ProtoReflect.Descriptor instead.
func (*PeerLag) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *PeerLag) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerLag) GetFreshnessMs() float64 {
	if x != nil {
		return x.FreshnessMs
	}
	return 0
}

func (x *PeerLag) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *PeerLag) GetReplicationLagMs() float64 {
	if x != nil {
		return x.ReplicationLagMs
	}
	return 0
}

func (x *PeerLag) GetPingMs() float64 {
	if x != nil {
		return x.PingMs
	}
	return 0
}

// Metadata injected by the gRPC proxy into One2Many responses.
type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineAddr string `protobuf:"bytes,1,opt,name=machine_addr,json=machineAddr,proto3" json:"machine_addr,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MachineId   string `protobuf:"bytes,3,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *Metadata) GetMachineAddr() string {
	if x != nil {
		return x.MachineAddr
	}
	return ""
}

func (x *Metadata) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Metadata) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

// Helper message for marshalling a single metadata field. Used by the proxy to
// inject metadata into response messages and to build error-only responses.
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *Empty) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EmptyResponse wraps repeated Empty for One2Many error concatenation.
type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Empty `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *EmptyResponse) GetMessages() []*Empty {
	if x != nil {
		return x.Messages
	}
	return nil
}

// PeerHealthReply is a single node's health report, compatible with One2Many proxy.
// The metadata field is injected by the proxy and is nil for direct (non-proxied) calls.
type PeerHealthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *Metadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NodeId   string       `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ntp      *ClockHealth `protobuf:"bytes,3,opt,name=ntp,proto3" json:"ntp,omitempty"`
	Peers    []*PeerLag   `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *PeerHealthReply) Reset() {
	*x = PeerHealthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerHealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHealthReply) ProtoMessage() {}

func (x *PeerHealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHealthReply.ProtoReflect.Descriptor instead.
func (*PeerHealthReply) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *PeerHealthReply) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PeerHealthReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerHealthReply) GetNtp() *ClockHealth {
	if x != nil {
		return x.Ntp
	}
	return nil
}

func (x *PeerHealthReply) GetPeers() []*PeerLag {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerHealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*PeerHealthReply `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *GetPeerHealthResponse) Reset() {
	*x = GetPeerHealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_daemon_pb_daemon_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerHealthResponse) ProtoMessage() {}

func (x *GetPeerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_pb_daemon_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerHealthResponse.ProtoReflect.Descriptor instead.
func (*GetPeerHealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_pb_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *GetPeerHealthResponse) GetMessages() []*PeerHealthReply {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_internal_daemon_pb_daemon_proto protoreflect.FileDescriptor

var file_internal_daemon_pb_daemon_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f,
	0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x22, 0x8d, 0x03, 0x0a, 0x0b, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x6f, 0x6f, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x69,
	0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12,
	0x2d, 0x0a, 0x12, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x77, 0x67, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x77, 0x67, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x65, 0x6c,
	0x70, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x72, 0x72,
	0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x72, 0x72,
	0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x70, 0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x41, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0xd3, 0x03, 0x0a, 0x0b,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x43, 0x69, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x67, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x67, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x67, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x5f, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x72, 0x72, 0x6f,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x70,
	0x69, 0x41, 0x64, 0x64, 0x72, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x47,
	0x6f, 0x73, 0x73, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x12, 0x2f, 0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x22, 0x47, 0x0a, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x75, 0x72, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x22, 0x6f, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x74, 0x70, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6e, 0x74, 0x70, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x74, 0x70, 0x5f, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x74, 0x70, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x74, 0x70, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x74, 0x70, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x9a, 0x02, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x0c, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x0b, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x22, 0xd3, 0x03, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x69, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x77,
	0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x77, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x77, 0x67, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x77, 0x67, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x65, 0x6c, 0x70, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65,
	0x6c, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x6f, 0x72, 0x72,
	0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69,
	0x6f, 0x6e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x70,
	0x69, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xe5, 0x02, 0x0a, 0x0c, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6c, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6c, 0x61, 0x67, 0x5f, 0x6d, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x67, 0x4d, 0x73, 0x22, 0x2f,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0x47, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x6f, 0x79,
	0x7a, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x14, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6c,
	0x6f, 0x79, 0x7a, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x64,
	0x4f, 0x72, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x17, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x1a, 0x0a, 0x18, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0xa2, 0x01, 0x0a, 0x07, 0x50, 0x65, 0x65, 0x72, 0x4c,
	0x61, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x66, 0x72, 0x65, 0x73, 0x68, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x61, 0x67, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x10, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x67,
	0x4d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x22, 0x62, 0x0a, 0x08, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22,
	0x34, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x6f,
	0x79, 0x7a, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x50, 0x65, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x6e, 0x74,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e,
	0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x03, 0x6e, 0x74, 0x70,
	0x12, 0x24, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x4c, 0x61, 0x67, 0x52,
	0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x4b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65,
	0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x32, 0x98, 0x05, 0x0a, 0x06, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x46,
	0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x1e, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4d, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a,
	0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x6c,
	0x6f, 0x79, 0x7a, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x19, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x6c,
	0x6f, 0x79, 0x7a, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0c,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70,
	0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a,
	0x10, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c,
	0x65, 0x12, 0x1e, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a,
	0x5a, 0x18, 0x70, 0x6c, 0x6f, 0x79, 0x7a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_daemon_pb_daemon_proto_rawDescOnce sync.Once
	file_internal_daemon_pb_daemon_proto_rawDescData = file_internal_daemon_pb_daemon_proto_rawDesc
)

func file_internal_daemon_pb_daemon_proto_rawDescGZIP() []byte {
	file_internal_daemon_pb_daemon_proto_rawDescOnce.Do(func() {
		file_internal_daemon_pb_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_daemon_pb_daemon_proto_rawDescData)
	})
	return file_internal_daemon_pb_daemon_proto_rawDescData
}

var file_internal_daemon_pb_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_daemon_pb_daemon_proto_goTypes = []any{
	(*NetworkSpec)(nil),              // 0: ployz.NetworkSpec
	(*ApplyNetworkSpecRequest)(nil),  // 1: ployz.ApplyNetworkSpecRequest
	(*ApplyResult)(nil),              // 2: ployz.ApplyResult
	(*DisableNetworkRequest)(nil),    // 3: ployz.DisableNetworkRequest
	(*DisableNetworkResponse)(nil),   // 4: ployz.DisableNetworkResponse
	(*GetStatusRequest)(nil),         // 5: ployz.GetStatusRequest
	(*ClockHealth)(nil),              // 6: ployz.ClockHealth
	(*NetworkStatus)(nil),            // 7: ployz.NetworkStatus
	(*GetIdentityRequest)(nil),       // 8: ployz.GetIdentityRequest
	(*Identity)(nil),                 // 9: ployz.Identity
	(*MachineEntry)(nil),             // 10: ployz.MachineEntry
	(*ListMachinesRequest)(nil),      // 11: ployz.ListMachinesRequest
	(*ListMachinesResponse)(nil),     // 12: ployz.ListMachinesResponse
	(*UpsertMachineRequest)(nil),     // 13: ployz.UpsertMachineRequest
	(*UpsertMachineResponse)(nil),    // 14: ployz.UpsertMachineResponse
	(*RemoveMachineRequest)(nil),     // 15: ployz.RemoveMachineRequest
	(*RemoveMachineResponse)(nil),    // 16: ployz.RemoveMachineResponse
	(*TriggerReconcileRequest)(nil),  // 17: ployz.TriggerReconcileRequest
	(*TriggerReconcileResponse)(nil), // 18: ployz.TriggerReconcileResponse
	(*GetPeerHealthRequest)(nil),     // 19: ployz.GetPeerHealthRequest
	(*PeerLag)(nil),                  // 20: ployz.PeerLag
	(*Metadata)(nil),                 // 21: ployz.Metadata
	(*Empty)(nil),                    // 22: ployz.Empty
	(*EmptyResponse)(nil),            // 23: ployz.EmptyResponse
	(*PeerHealthReply)(nil),          // 24: ployz.PeerHealthReply
	(*GetPeerHealthResponse)(nil),    // 25: ployz.GetPeerHealthResponse
}
var file_internal_daemon_pb_daemon_proto_depIdxs = []int32{
	0,  // 0: ployz.ApplyNetworkSpecRequest.spec:type_name -> ployz.NetworkSpec
	6,  // 1: ployz.NetworkStatus.clock_health:type_name -> ployz.ClockHealth
	10, // 2: ployz.ListMachinesResponse.machines:type_name -> ployz.MachineEntry
	10, // 3: ployz.UpsertMachineRequest.machine:type_name -> ployz.MachineEntry
	21, // 4: ployz.Empty.metadata:type_name -> ployz.Metadata
	22, // 5: ployz.EmptyResponse.messages:type_name -> ployz.Empty
	21, // 6: ployz.PeerHealthReply.metadata:type_name -> ployz.Metadata
	6,  // 7: ployz.PeerHealthReply.ntp:type_name -> ployz.ClockHealth
	20, // 8: ployz.PeerHealthReply.peers:type_name -> ployz.PeerLag
	24, // 9: ployz.GetPeerHealthResponse.messages:type_name -> ployz.PeerHealthReply
	1,  // 10: ployz.Daemon.ApplyNetworkSpec:input_type -> ployz.ApplyNetworkSpecRequest
	3,  // 11: ployz.Daemon.DisableNetwork:input_type -> ployz.DisableNetworkRequest
	5,  // 12: ployz.Daemon.GetStatus:input_type -> ployz.GetStatusRequest
	8,  // 13: ployz.Daemon.GetIdentity:input_type -> ployz.GetIdentityRequest
	11, // 14: ployz.Daemon.ListMachines:input_type -> ployz.ListMachinesRequest
	13, // 15: ployz.Daemon.UpsertMachine:input_type -> ployz.UpsertMachineRequest
	15, // 16: ployz.Daemon.RemoveMachine:input_type -> ployz.RemoveMachineRequest
	17, // 17: ployz.Daemon.TriggerReconcile:input_type -> ployz.TriggerReconcileRequest
	19, // 18: ployz.Daemon.GetPeerHealth:input_type -> ployz.GetPeerHealthRequest
	2,  // 19: ployz.Daemon.ApplyNetworkSpec:output_type -> ployz.ApplyResult
	4,  // 20: ployz.Daemon.DisableNetwork:output_type -> ployz.DisableNetworkResponse
	7,  // 21: ployz.Daemon.GetStatus:output_type -> ployz.NetworkStatus
	9,  // 22: ployz.Daemon.GetIdentity:output_type -> ployz.Identity
	12, // 23: ployz.Daemon.ListMachines:output_type -> ployz.ListMachinesResponse
	14, // 24: ployz.Daemon.UpsertMachine:output_type -> ployz.UpsertMachineResponse
	16, // 25: ployz.Daemon.RemoveMachine:output_type -> ployz.RemoveMachineResponse
	18, // 26: ployz.Daemon.TriggerReconcile:output_type -> ployz.TriggerReconcileResponse
	25, // 27: ployz.Daemon.GetPeerHealth:output_type -> ployz.GetPeerHealthResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_daemon_pb_daemon_proto_init() }
func file_internal_daemon_pb_daemon_proto_init() {
	if File_internal_daemon_pb_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_daemon_pb_daemon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyNetworkSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DisableNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DisableNetworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ClockHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MachineEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListMachinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ListMachinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertMachineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertMachineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMachineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMachineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerReconcileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerReconcileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetPeerHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*PeerLag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*PeerHealthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_daemon_pb_daemon_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*GetPeerHealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_daemon_pb_daemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_daemon_pb_daemon_proto_goTypes,
		DependencyIndexes: file_internal_daemon_pb_daemon_proto_depIdxs,
		MessageInfos:      file_internal_daemon_pb_daemon_proto_msgTypes,
	}.Build()
	File_internal_daemon_pb_daemon_proto = out.File
	file_internal_daemon_pb_daemon_proto_rawDesc = nil
	file_internal_daemon_pb_daemon_proto_goTypes = nil
	file_internal_daemon_pb_daemon_proto_depIdxs = nil
}
