[package]
name = "ployz-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-build-api = { path = "../ployz-build-api" }
ployz-model = { path = "../ployz-model" }
ployz-operation-store = { path = "../ployz-operation-store" }
ployz-runtime-api = { path = "../ployz-runtime-api" }
ployz-time = { path = "../ployz-time" }
async-trait = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["rt", "process", "io-util", "time"] }

[lints]
workspace = true
