// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/controlplane/pb/daemon.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daemon_ApplyNetworkSpec_FullMethodName   = "/ployz.Daemon/ApplyNetworkSpec"
	Daemon_DisableNetwork_FullMethodName     = "/ployz.Daemon/DisableNetwork"
	Daemon_GetStatus_FullMethodName          = "/ployz.Daemon/GetStatus"
	Daemon_GetIdentity_FullMethodName        = "/ployz.Daemon/GetIdentity"
	Daemon_ListMachines_FullMethodName       = "/ployz.Daemon/ListMachines"
	Daemon_UpsertMachine_FullMethodName      = "/ployz.Daemon/UpsertMachine"
	Daemon_RemoveMachine_FullMethodName      = "/ployz.Daemon/RemoveMachine"
	Daemon_GetPeerHealth_FullMethodName      = "/ployz.Daemon/GetPeerHealth"
	Daemon_PlanDeploy_FullMethodName         = "/ployz.Daemon/PlanDeploy"
	Daemon_ApplyDeploy_FullMethodName        = "/ployz.Daemon/ApplyDeploy"
	Daemon_ListDeployments_FullMethodName    = "/ployz.Daemon/ListDeployments"
	Daemon_RemoveNamespace_FullMethodName    = "/ployz.Daemon/RemoveNamespace"
	Daemon_ReadContainerState_FullMethodName = "/ployz.Daemon/ReadContainerState"
)

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonClient interface {
	ApplyNetworkSpec(ctx context.Context, in *ApplyNetworkSpecRequest, opts ...grpc.CallOption) (*ApplyResult, error)
	DisableNetwork(ctx context.Context, in *DisableNetworkRequest, opts ...grpc.CallOption) (*DisableNetworkResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*NetworkStatus, error)
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Identity, error)
	ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error)
	UpsertMachine(ctx context.Context, in *UpsertMachineRequest, opts ...grpc.CallOption) (*UpsertMachineResponse, error)
	RemoveMachine(ctx context.Context, in *RemoveMachineRequest, opts ...grpc.CallOption) (*RemoveMachineResponse, error)
	GetPeerHealth(ctx context.Context, in *GetPeerHealthRequest, opts ...grpc.CallOption) (*GetPeerHealthResponse, error)
	// PlanDeploy parses compose YAML and returns a dry-run execution plan.
	PlanDeploy(ctx context.Context, in *PlanDeployRequest, opts ...grpc.CallOption) (*PlanDeployResponse, error)
	// ApplyDeploy executes a deploy and streams progress + final result.
	ApplyDeploy(ctx context.Context, in *ApplyDeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployProgressEvent], error)
	// ListDeployments returns deployment rows for a namespace.
	ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error)
	// RemoveNamespace removes all namespace containers on this machine.
	RemoveNamespace(ctx context.Context, in *RemoveNamespaceRequest, opts ...grpc.CallOption) (*RemoveNamespaceResponse, error)
	// ReadContainerState returns actual local container runtime state.
	ReadContainerState(ctx context.Context, in *ReadContainerStateRequest, opts ...grpc.CallOption) (*ReadContainerStateResponse, error)
}

type daemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonClient(cc grpc.ClientConnInterface) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) ApplyNetworkSpec(ctx context.Context, in *ApplyNetworkSpecRequest, opts ...grpc.CallOption) (*ApplyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResult)
	err := c.cc.Invoke(ctx, Daemon_ApplyNetworkSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) DisableNetwork(ctx context.Context, in *DisableNetworkRequest, opts ...grpc.CallOption) (*DisableNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableNetworkResponse)
	err := c.cc.Invoke(ctx, Daemon_DisableNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*NetworkStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStatus)
	err := c.cc.Invoke(ctx, Daemon_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, Daemon_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMachinesResponse)
	err := c.cc.Invoke(ctx, Daemon_ListMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) UpsertMachine(ctx context.Context, in *UpsertMachineRequest, opts ...grpc.CallOption) (*UpsertMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMachineResponse)
	err := c.cc.Invoke(ctx, Daemon_UpsertMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) RemoveMachine(ctx context.Context, in *RemoveMachineRequest, opts ...grpc.CallOption) (*RemoveMachineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMachineResponse)
	err := c.cc.Invoke(ctx, Daemon_RemoveMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) GetPeerHealth(ctx context.Context, in *GetPeerHealthRequest, opts ...grpc.CallOption) (*GetPeerHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeerHealthResponse)
	err := c.cc.Invoke(ctx, Daemon_GetPeerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) PlanDeploy(ctx context.Context, in *PlanDeployRequest, opts ...grpc.CallOption) (*PlanDeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanDeployResponse)
	err := c.cc.Invoke(ctx, Daemon_PlanDeploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ApplyDeploy(ctx context.Context, in *ApplyDeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Daemon_ServiceDesc.Streams[0], Daemon_ApplyDeploy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyDeployRequest, DeployProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_ApplyDeployClient = grpc.ServerStreamingClient[DeployProgressEvent]

func (c *daemonClient) ListDeployments(ctx context.Context, in *ListDeploymentsRequest, opts ...grpc.CallOption) (*ListDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeploymentsResponse)
	err := c.cc.Invoke(ctx, Daemon_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) RemoveNamespace(ctx context.Context, in *RemoveNamespaceRequest, opts ...grpc.CallOption) (*RemoveNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNamespaceResponse)
	err := c.cc.Invoke(ctx, Daemon_RemoveNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ReadContainerState(ctx context.Context, in *ReadContainerStateRequest, opts ...grpc.CallOption) (*ReadContainerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadContainerStateResponse)
	err := c.cc.Invoke(ctx, Daemon_ReadContainerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
// All implementations must embed UnimplementedDaemonServer
// for forward compatibility.
type DaemonServer interface {
	ApplyNetworkSpec(context.Context, *ApplyNetworkSpecRequest) (*ApplyResult, error)
	DisableNetwork(context.Context, *DisableNetworkRequest) (*DisableNetworkResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*NetworkStatus, error)
	GetIdentity(context.Context, *GetIdentityRequest) (*Identity, error)
	ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error)
	UpsertMachine(context.Context, *UpsertMachineRequest) (*UpsertMachineResponse, error)
	RemoveMachine(context.Context, *RemoveMachineRequest) (*RemoveMachineResponse, error)
	GetPeerHealth(context.Context, *GetPeerHealthRequest) (*GetPeerHealthResponse, error)
	// PlanDeploy parses compose YAML and returns a dry-run execution plan.
	PlanDeploy(context.Context, *PlanDeployRequest) (*PlanDeployResponse, error)
	// ApplyDeploy executes a deploy and streams progress + final result.
	ApplyDeploy(*ApplyDeployRequest, grpc.ServerStreamingServer[DeployProgressEvent]) error
	// ListDeployments returns deployment rows for a namespace.
	ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error)
	// RemoveNamespace removes all namespace containers on this machine.
	RemoveNamespace(context.Context, *RemoveNamespaceRequest) (*RemoveNamespaceResponse, error)
	// ReadContainerState returns actual local container runtime state.
	ReadContainerState(context.Context, *ReadContainerStateRequest) (*ReadContainerStateResponse, error)
	mustEmbedUnimplementedDaemonServer()
}

// UnimplementedDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServer struct{}

func (UnimplementedDaemonServer) ApplyNetworkSpec(context.Context, *ApplyNetworkSpecRequest) (*ApplyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNetworkSpec not implemented")
}
func (UnimplementedDaemonServer) DisableNetwork(context.Context, *DisableNetworkRequest) (*DisableNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableNetwork not implemented")
}
func (UnimplementedDaemonServer) GetStatus(context.Context, *GetStatusRequest) (*NetworkStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServer) GetIdentity(context.Context, *GetIdentityRequest) (*Identity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedDaemonServer) ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (UnimplementedDaemonServer) UpsertMachine(context.Context, *UpsertMachineRequest) (*UpsertMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMachine not implemented")
}
func (UnimplementedDaemonServer) RemoveMachine(context.Context, *RemoveMachineRequest) (*RemoveMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMachine not implemented")
}
func (UnimplementedDaemonServer) GetPeerHealth(context.Context, *GetPeerHealthRequest) (*GetPeerHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerHealth not implemented")
}
func (UnimplementedDaemonServer) PlanDeploy(context.Context, *PlanDeployRequest) (*PlanDeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanDeploy not implemented")
}
func (UnimplementedDaemonServer) ApplyDeploy(*ApplyDeployRequest, grpc.ServerStreamingServer[DeployProgressEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ApplyDeploy not implemented")
}
func (UnimplementedDaemonServer) ListDeployments(context.Context, *ListDeploymentsRequest) (*ListDeploymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedDaemonServer) RemoveNamespace(context.Context, *RemoveNamespaceRequest) (*RemoveNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNamespace not implemented")
}
func (UnimplementedDaemonServer) ReadContainerState(context.Context, *ReadContainerStateRequest) (*ReadContainerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadContainerState not implemented")
}
func (UnimplementedDaemonServer) mustEmbedUnimplementedDaemonServer() {}
func (UnimplementedDaemonServer) testEmbeddedByValue()                {}

// UnsafeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServer will
// result in compilation errors.
type UnsafeDaemonServer interface {
	mustEmbedUnimplementedDaemonServer()
}

func RegisterDaemonServer(s grpc.ServiceRegistrar, srv DaemonServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daemon_ServiceDesc, srv)
}

func _Daemon_ApplyNetworkSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNetworkSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ApplyNetworkSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ApplyNetworkSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ApplyNetworkSpec(ctx, req.(*ApplyNetworkSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_DisableNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).DisableNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_DisableNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).DisableNetwork(ctx, req.(*DisableNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ListMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListMachines(ctx, req.(*ListMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_UpsertMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).UpsertMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_UpsertMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).UpsertMachine(ctx, req.(*UpsertMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_RemoveMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).RemoveMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_RemoveMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).RemoveMachine(ctx, req.(*RemoveMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_GetPeerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).GetPeerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_GetPeerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).GetPeerHealth(ctx, req.(*GetPeerHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_PlanDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).PlanDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_PlanDeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).PlanDeploy(ctx, req.(*PlanDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ApplyDeploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApplyDeployRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).ApplyDeploy(m, &grpc.GenericServerStream[ApplyDeployRequest, DeployProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_ApplyDeployServer = grpc.ServerStreamingServer[DeployProgressEvent]

func _Daemon_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListDeployments(ctx, req.(*ListDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_RemoveNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).RemoveNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_RemoveNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).RemoveNamespace(ctx, req.(*RemoveNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ReadContainerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContainerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ReadContainerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ReadContainerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ReadContainerState(ctx, req.(*ReadContainerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Daemon_ServiceDesc is the grpc.ServiceDesc for Daemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ployz.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyNetworkSpec",
			Handler:    _Daemon_ApplyNetworkSpec_Handler,
		},
		{
			MethodName: "DisableNetwork",
			Handler:    _Daemon_DisableNetwork_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Daemon_GetStatus_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _Daemon_GetIdentity_Handler,
		},
		{
			MethodName: "ListMachines",
			Handler:    _Daemon_ListMachines_Handler,
		},
		{
			MethodName: "UpsertMachine",
			Handler:    _Daemon_UpsertMachine_Handler,
		},
		{
			MethodName: "RemoveMachine",
			Handler:    _Daemon_RemoveMachine_Handler,
		},
		{
			MethodName: "GetPeerHealth",
			Handler:    _Daemon_GetPeerHealth_Handler,
		},
		{
			MethodName: "PlanDeploy",
			Handler:    _Daemon_PlanDeploy_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _Daemon_ListDeployments_Handler,
		},
		{
			MethodName: "RemoveNamespace",
			Handler:    _Daemon_RemoveNamespace_Handler,
		},
		{
			MethodName: "ReadContainerState",
			Handler:    _Daemon_ReadContainerState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ApplyDeploy",
			Handler:       _Daemon_ApplyDeploy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/controlplane/pb/daemon.proto",
}
