[package]
name = "mvp-p2panda-06-spike"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
publish = false

[workspace]

[dependencies]
p2panda-auth = { version = "0.6.0", features = ["serde", "test_utils"] }
p2panda-core = { version = "0.6.0", features = ["test_utils"] }
p2panda-net = "0.6.0"
p2panda-store = { version = "0.6.0", features = ["sqlite", "test_utils"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
