[package]
name = "ployz-volume"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-volume-api = { path = "../ployz-volume-api" }

[dev-dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }

[lints]
workspace = true
