[package]
name = "ployz-store-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-error = { path = "../ployz-error" }
ployz-model = { path = "../ployz-model" }
ployz-spec = { path = "../ployz-spec" }
serde = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "macros", "time"] }
async-trait = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
