CREATE TABLE IF NOT EXISTS machines (
    id TEXT NOT NULL PRIMARY KEY,
    public_key BLOB NOT NULL DEFAULT X'',
    overlay_ip TEXT NOT NULL DEFAULT '',
    endpoints TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS invites (
    id TEXT NOT NULL PRIMARY KEY,
    expires_at INTEGER NOT NULL DEFAULT 0
);
