# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ployz < Formula
  desc "Ployz CLI, daemon, and runtime"
  homepage "https://github.com/getployz/ployz"
  version "0.1.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getployz/ployz/releases/download/v0.1.0-alpha.2/ployz_0.1.0-alpha.2_darwin_amd64.tar.gz"
      sha256 "dc02a9e17f283b7d8729433b70ba2fe6bf17addca4243943509284905869bf25"

      def install
        bin.install "ployz"
        bin.install "ployzd"
        bin.install "ployz-runtime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getployz/ployz/releases/download/v0.1.0-alpha.2/ployz_0.1.0-alpha.2_darwin_arm64.tar.gz"
      sha256 "380135588ba4db8b0f0c71fe3dbe92607af1acf87d91622008bbe3d76a7b2aad"

      def install
        bin.install "ployz"
        bin.install "ployzd"
        bin.install "ployz-runtime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getployz/ployz/releases/download/v0.1.0-alpha.2/ployz_0.1.0-alpha.2_linux_amd64.tar.gz"
      sha256 "fe0b8ef13e1ef78804cbe16a5d9ff55898fd631795b434e415343e0097c39868"
      def install
        bin.install "ployz"
        bin.install "ployzd"
        bin.install "ployz-runtime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getployz/ployz/releases/download/v0.1.0-alpha.2/ployz_0.1.0-alpha.2_linux_arm64.tar.gz"
      sha256 "e93fd6dc5a70d521d20829ce83b483d82f6b6555e177df6e7961a51c85210b54"
      def install
        bin.install "ployz"
        bin.install "ployzd"
        bin.install "ployz-runtime"
      end
    end
  end

  service do
    run [opt_bin/"ployz", "dev", "run"]
    keep_alive true
    log_path var/"log/ployz.log"
    error_log_path var/"log/ployz.log"
  end

  def caveats
    <<~EOS
      The formula installs three binaries:
        - ployz
        - ployzd
        - ployz-runtime

      To run daemon and runtime together in user mode:
        ployz dev run
    EOS
  end

  test do
    system "#{bin}/ployz", "--help"
    system "#{bin}/ployzd", "--help"
    system "#{bin}/ployz-runtime", "--help"
  end
end
