[package]
name = "ployzd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "ployzd"
path = "src/main.rs"

[features]
ebpf-native = ["ployz-orchestrator/ebpf-native"]

[dependencies]
ployz-api = { path = "../ployz-api" }
ployz-cert-backends = { path = "../ployz-cert-backends" }
ployz-config = { path = "../ployz-config" }
ployz-metrics = { path = "../ployz-metrics" }
ployz-nats = { path = "../ployz-nats" }
ployz-orchestrator = { path = "../ployz-orchestrator" }
ployz-runtime-api = { path = "../ployz-runtime-api" }
ployz-runtime-backends = { path = "../ployz-runtime-backends" }
ployz-sdk = { path = "../ployz-sdk" }
ployz-store-api = { path = "../ployz-store-api" }
ployz-types = { path = "../ployz-types" }
ployz-gateway-config = { path = "../ployz-gateway-config" }
ployz-dns-config = { path = "../ployz-dns-config" }
ployz-install = { path = "../ployz-install" }
axum = { workspace = true }
futures-util = { workspace = true }
async-nats = "0.47"
clap = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
ipnet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["process", "fs", "io-std"] }
tokio-util = { workspace = true, features = ["io"] }
tar = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }
prometheus = { workspace = true }
ed25519-dalek = "2"
uuid = { workspace = true }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tower = "0.5"

[lints]
workspace = true
