#!/usr/bin/env bash
# Captures Config Store CLI output against the hidden in-process SQLite Store.
#   store/run.sh [PARENT]   raw captures into a fresh mktemp -d under PARENT (default /tmp)
#   publish.sh DIR       scrubs them and copies them over the tracked ones
set -euo pipefail
shopt -s inherit_errexit
# Ctrl-C stops the run before .ok, even when the command it interrupted
# (script, ployz) swallowed the signal and exited normally.
trap 'exit 130' INT
trap 'exit 143' TERM
DOCS=$(cd -- "$(dirname -- "$0")/.." && pwd) || exit 1
CORE=$(cd -- "$DOCS/../.." && pwd) || exit 1
CAPTURES=$("$DOCS/capture-dir.sh" "${1:-}") || exit 1
SCRATCH=$(mktemp -d /tmp/ployz-cli-outputs-store.XXXXXX) || exit 1
readonly DOCS CORE CAPTURES SCRATCH
trap 'rm -rf "$SCRATCH"' EXIT
echo "raw captures in $CAPTURES"
mkdir -p "$SCRATCH/home" "$SCRATCH/work" "$SCRATCH/other"
cap=$DOCS/cap.sh
export PLOYZ_BIN=${PLOYZ_BIN:-$CORE/target/debug/ployz}
B=$PLOYZ_BIN

# Same isolation as tests/config_cli.rs: own HOME and config, local Store, no Cloud.
export HOME=$SCRATCH/home
export PLOYZ_CONFIG=$SCRATCH/home/config.yaml
export PLOYZ_STORE=sqlite:$SCRATCH/store.db
unset PLOYZ_TOKEN PLOYZ_CLOUD_URL PLOYZ_PROJECT PLOYZ_ENV PLOYZ_CONTEXT PLOYZ_CONNECT
unset NO_COLOR
cd "$SCRATCH/work" || exit 1

# c FILE "TITLE" ARGS...   capture (pipe + TTY rerun)
c() { local f=$1 t=$2; shift 2; "$cap" "$CAPTURES/$f.md" "$t" -- "$B" "$@"; }
# m FILE "TITLE" ARGS...   capture a mutating command once (no TTY rerun)
m() { local f=$1 t=$2; shift 2; CAP_TTY=0 "$cap" "$CAPTURES/$f.md" "$t" -- "$B" "$@"; }
# x FILE "TITLE" CMD...   capture an arbitrary command line (env overrides etc.)
x() { local f=$1 t=$2; shift 2; "$cap" "$CAPTURES/$f.md" "$t" -- "$@"; }
# need m|x ...   a capture later captures depend on; its failure stops the run
need() { CAP_MUST=1 "$@"; }
# s ARGS...   setup step, not captured
s() { "$B" "$@" >/dev/null 2>&1 || { echo "setup step failed: ployz $*" >&2; exit 1; }; }
# trunc FILE "TITLE" LINES ARGS...   capture, keeping the first LINES of stdout
trunc() {
  local f=$1 t=$2 n=$3; shift 3
  local o e code=0
  o=$(mktemp) || exit 1
  e=$(mktemp) || exit 1
  "$B" "$@" </dev/null >"$o" 2>"$e" || code=$?
  {
    echo "### $t"; echo; echo '```console'; echo "\$ ployz $*"; echo "# exit $code"; echo '```'
    echo; echo "stdout ($(wc -l <"$o") lines, first $n shown):"; echo '```'; head -n "$n" "$o"; echo '...'; echo '```'
    if [ -s "$e" ]; then echo; echo 'stderr:'; echo '```'; cat "$e"; echo '```'; fi
    echo
  } >>"$CAPTURES/$f.md"
  rm -f "$o" "$e"
}
# tty FILE "TITLE" "INPUT" ARGS...   run under a pty, typing INPUT after 1s
tty() {
  local f=$1 t=$2 input=$3; shift 3
  local cmd; printf -v cmd '%q ' "$B" "$@"
  {
    echo "### $t (TTY, typed: ${input:-<Enter>})"; echo; echo '```console'; echo "\$ ployz $*"
    (sleep 1; printf '%s\n' "$input"; sleep 2) | script -qec "$cmd" /dev/null 2>&1 | sed 's/\r$//' || true
    echo '```'; echo
  } >>"$CAPTURES/$f.md"
}
note() { printf '%s\n\n' "$2" >>"$CAPTURES/$1.md"; }

for f in project env service settings staging context help errors; do
  printf '# ployz %s outputs (local SQLite Store)\n\nGenerated by store/run.sh against `PLOYZ_STORE=sqlite:...`, isolated HOME. Each block: pipe run (stdout/stderr split); `%s.ansi` holds the TTY rerun.\n\n' "$f" "$f" >"$CAPTURES/$f.md"
done

########## project ##########
c project "project ls (empty Store)" project ls
c project "project ls --json (empty Store)" --json project ls
c context "status (no Project yet)" status
c context "status --json (no Project yet)" --json status
need m project "project new" project new shop
need m project "project new --json" --json project new blog
m project "project new: name taken" project new shop
m project "project new --json: name taken" --json project new shop
m project "project new: invalid name" project new "Bad Name!"
m project "project new --json: invalid name" --json project new "Bad Name!"
c project "project ls" project ls
c project "project ls --json" --json project ls
need m project "project rename" project rename blog journal
need m project "project rename --json" --json project rename journal blog
m project "project rename: unknown Project" project rename nope other
m project "project rename: name taken" project rename blog shop
s project new scratch1
m project "project rm without --confirm" project rm scratch1
m project "project rm --json without --confirm" --json project rm scratch1
m project "project rm: --confirm mismatch" project rm scratch1 --confirm scratch
m project "project rm --confirm" project rm scratch1 --confirm scratch1
s project new scratch2
m project "project rm --json --confirm" --json project rm scratch2 --confirm scratch2
m project "project rm: unknown Project" project rm nope --confirm nope
tty project "project rm in a terminal, no --confirm" "" project rm blog

# Two Projects now: commands that default to "the only Project" must refuse.
c errors "get: two Projects, none chosen" get
c errors "get --json: two Projects, none chosen" --json get
c errors "service ls: unknown --project" service ls --project nope
c errors "service ls --json: unknown --project" --json service ls --project nope
c errors "get: unknown --env" get --project shop --env nope

########## service ##########
export PLOYZ_PROJECT=shop
c service "service ls (no Services)" service ls
c service "service ls --json (no Services)" --json service ls
c settings "get (no Services)" get
need m service "service add --image" service add web --image nginx:1.27
need m service "service add --json --image" --json service add db --image postgres:16
need m service "service add (empty Service)" service add worker
m service "service add: name taken" service add web --image nginx:1.27
m service "service add --json: name taken" --json service add web --image nginx:1.27
m service "service add: invalid name" service add Web_1
m service "service add: --image and --repo together" service add api --image a:1 --repo acme/api
m service "service add --repo (needs GitHub)" service add api --repo acme/api
c service "service ls" service ls
c service "service ls --json" --json service ls
need m service "service rename" service rename worker jobs
need m service "service rename --json" --json service rename jobs worker
m service "service rename: unknown Service" service rename nope other
m service "service rm" service rm worker
m service "service rm: unknown Service" service rm nope
s service add cache --image redis:7
m service "service rm --json" --json service rm cache
c service "service ls (after rm)" service ls

########## settings: set ##########
need m settings "set one value" set web.replicas=3
need m settings "set --json one value" --json set web.replicas=2
need m settings "set several values" set web.env.LOG_LEVEL=info web.env.PORT=8080 db.replicas=1
need m settings "set env var with a reference" set 'web.env.DB_URL=postgres://${{ db.PLOYZ_PRIVATE_DOMAIN }}/app'
printf 's3cr3t' | CAP_TTY=0 "$cap" "$CAPTURES/settings.md" "set --secret (value on stdin)" -- "$B" set web.env.API_KEY --secret
printf 's3cr3t2' | CAP_TTY=0 "$cap" "$CAPTURES/settings.md" "set --json --secret (value on stdin)" -- "$B" --json set web.env.API_KEY2 --secret
note settings 'Note: cap.sh feeds </dev/null, so the two --secret captures above read an empty stdin; see the piped runs below.'
{
  echo '### set --secret, value piped'; echo; echo '```console'; echo '$ printf s3cr3t | ployz set web.env.API_KEY --secret'
  rc=0; printf 's3cr3t' | "$B" set web.env.API_KEY --secret 2>&1 || rc=$?; echo "# exit $rc"
  echo '$ printf s3cr3t | ployz --json set web.env.API_KEY2 --secret'
  rc=0; printf 's3cr3t' | "$B" --json set web.env.API_KEY2 --secret 2>&1 || rc=$?; echo "# exit $rc"
  echo '```'; echo
} >>"$CAPTURES/settings.md"
need m settings "set --patch" set web --patch '{"healthcheck":{"path":"/healthz"}}'
m settings "set mount: whole mounts object" set 'db.mounts={"pgdata":"/var/lib/postgresql/data"}'
m settings "set mount: no such Volume" set db.mounts.pgdata=/var/lib/postgresql/data
need m settings "volume add (setup for mounts)" volume add pgdata
need m settings "set mount (volume)" set db.mounts.pgdata=/var/lib/postgresql/data
m settings "set mount: relative path" set db.mounts.cache=data
printf 'A=1\nB=two\n' >"$SCRATCH/web.env"
need m settings "set --from-env-file" set web --from-env-file "$SCRATCH/web.env"
m settings "set: unknown Service" set nope.replicas=2
m settings "set --json: unknown Service" --json set nope.replicas=2
m settings "set: unknown Setting" set web.replicaz=2
m settings "set --json: unknown Setting" --json set web.replicaz=2
m settings "set: bad value type" set web.replicas=lots
m settings "set --json: bad value type" --json set web.replicas=lots
m settings "set: missing =" set web.replicas
m settings "set: --expect stale revision" set web.replicas=4 --expect 1
m settings "set --secret on a non-env path" set web.replicas --secret

########## settings: get / unset / explain / schema ##########
c settings "get (all Services)" get
c settings "get --json (all Services)" --json get
c settings "get --all" get --all
c settings "get one Service" get web
c settings "get --json one Service" --json get web
c settings "get one Setting" get web.replicas
c settings "get --json one Setting" --json get web.replicas
c settings "get one env var" get web.env.LOG_LEVEL
c settings "get a secret env var" get web.env.API_KEY
c settings "get: unknown Service" get nope
c settings "get --json: unknown Service" --json get nope
c settings "get: unknown Setting" get web.replicaz
c settings "get: unset env var" get web.env.MISSING
m settings "unset one Setting" unset web.replicas
m settings "unset --json env var" --json unset web.env.PORT
m settings "unset: unknown Setting" unset web.replicaz
m settings "unset: variable not set" unset web.env.MISSING
c settings "explain" explain web.replicas
c settings "explain --json" --json explain web.replicas
c settings "explain env" explain web.env
c settings "explain: unknown Setting" explain web.replicaz
c settings "explain --json: unknown Setting" --json explain web.replicaz
c settings "explain: Service only" explain web
trunc settings "schema (human)" 40 schema
trunc settings "schema --json" 40 --json schema
trunc settings "schema one Service" 40 schema web
c settings "schema one Setting" schema web.replicas
c settings "schema --json one Setting" --json schema web.replicas
c settings "schema: unknown path" schema web.replicaz

########## staging ##########
c staging "diff (staged changes)" diff
c staging "diff --json (staged changes)" --json diff
c context "status (staged changes)" status
c context "status --json (staged changes)" --json status
m staging "discard one Setting" discard web.healthcheck
m staging "discard --json one Setting" --json discard web.env.B
m staging "discard: unknown path" discard nope
m staging "publish: stale --version" publish --version 1:0:0.0
need m staging "publish" publish
c staging "diff (after publish, not deployed)" diff
m staging "publish again (nothing new)" publish
m staging "publish --json again" --json publish
s set web.replicas=4
m staging "publish --json" --json publish
s project new empty
c staging "diff (nothing staged)" diff --project empty
c staging "diff --json (nothing staged)" --json diff --project empty
m staging "discard (nothing staged)" discard --project empty
m staging "discard --json (nothing staged)" --json discard --project empty
m staging "publish (nothing staged)" publish --project empty
s set web.env.LOG_LEVEL=debug
need m staging "discard everything" discard
m staging "discard: stale --version" discard --version 1:0:0.0
c staging "diff (everything discarded)" diff

# Discarding everything dropped the never-deployed Services; bring them back.
s service add web --image nginx:1.27
s service add db --image postgres:16
s volume add pgdata
s set db.mounts.pgdata=/var/lib/postgresql/data
s set 'web.env.DB_URL=postgres://${{ db.PLOYZ_PRIVATE_DOMAIN }}/app'
s publish

########## env ##########
c env "env ls" env ls
c env "env ls --json" --json env ls
need m env "env new" env new staging
need m env "env new --json" --json env new qa
m env "env new: name taken" env new staging
m env "env new: invalid name" env new "Not Valid"
m env "env new: unknown --project" env new x --project nope
need m env "env default" env default staging
need m env "env default --json" --json env default production
m env "env default: unknown Environment" env default nope
m env "env setup" env setup --setup 'web=bin/migrate'
m env "env setup --json" --json env setup --setup 'web=bin/migrate' --setup 'db=psql -f seed.sql'
m env "env setup: bad SERVICE=COMMAND" env setup --setup web
m env "env setup: unknown Service" env setup --setup 'nope=x'
m env "env setup --clear" env setup --clear
need m env "env branch --copy" env branch fix-web --copy web
need m env "env branch --json --copy" --json env branch fix-db --copy db
m env "env branch: unknown node" env branch fix-x --copy nope
m env "env branch: name taken" env branch fix-web --copy web
need m env "env branch --keep --setup" env branch long --copy web --keep --setup 'web=bin/seed'
c env "env ls (with Branches)" env ls
c env "env ls --json (with Branches)" --json env ls
m env "env sync --to: nothing to sync" env sync --to --env fix-web
m env "env sync --json --to: nothing to sync" --json env sync --to --env fix-web
m env "env sync without --to/--from (clap)" env sync --env fix-web
m env "env sync --plan --close (clap)" env sync --to --plan --close
s set --env fix-web web.image=nginx:1.28 web.env.DEBUG=1 web.env.NEW=1
c env "env sync --to --plan" env sync --to --plan --env fix-web
c env "env sync --json --to --plan" --json env sync --to --plan --env fix-web
m env "env sync: stale --version" env sync --to --env fix-web --version 0:0
m env "env sync --only unknown" env sync --to --env fix-web --only api
need m env "env sync --to --only" env sync --to --env fix-web --only web.env.DEBUG
need m env "env sync --json --to" --json env sync --to --env fix-web
c staging "diff in the Parent after a Sync" diff
c staging "diff --json in the Parent after a Sync" --json diff
m env "env sync --undo: unknown Sync" env sync --undo nope
m env "env keep" env keep --env fix-web
m env "env keep --json --off" --json env keep --env fix-web --off
m env "env keep: not a Branch" env keep --env staging
m env "env never-sync" env never-sync web.env.DEBUG --env fix-web
m env "env never-sync --json --off" --json env never-sync web.env.DEBUG --env fix-web --off
m env "env never-sync: unknown row" env never-sync api.env.KEY --env fix-web
m env "env never-sync: no row (clap)" env never-sync --env fix-web
m env "env copy: node already copied" env copy web --env fix-web
m env "env copy" env copy db --env fix-web
m env "env copy --json" --json env copy db --env long
m env "env copy: not a Branch" env copy web --env staging
m env "env branch --live: nothing uses it" env branch livex --copy db --live web
m env "env branch --live: Parent never deployed" env branch livebr --copy web --live db
note env 'A successful `env copy` needs a Live Node, which needs a running Deployment of the Parent (a cluster); not capturable on the local Store.'
c env "env pr" env pr
c env "env pr --json" --json env pr
m env "env pr --on: no repository" env pr acme/app --on
m env "env shutdown (never deployed)" env shutdown qa
m env "env shutdown --json (never deployed)" --json env shutdown qa
m env "env rm without --confirm" env rm qa
m env "env rm --json without --confirm" --json env rm qa
m env "env rm: --confirm mismatch" env rm qa --confirm qa
m env "env rm --confirm" env rm qa --confirm shop/qa
m env "env rm --json --confirm" --json env rm fix-db --confirm shop/fix-db
m env "env rm: Default Environment" env rm production --confirm shop/production
m env "env rm: unknown Environment" env rm nope --confirm shop/nope

########## context: link / ctx / status ##########
s set web.replicas=2 web.env.FEATURE=on
unset PLOYZ_PROJECT
c context "status (two Projects, no link)" status
m context "link: two Projects, none chosen" link
need m context "link --project" link --project shop
c context "status (linked, staged changes)" status
c context "status --json (linked)" --json status
(cd "$SCRATCH/other" || exit 1; CAP_TTY=0 "$cap" "$CAPTURES/context.md" "link --json --project --env (another directory)" -- "$B" --json link --project shop --env staging)
m context "link: unknown Environment" link --project shop --env nope
c context "status with --env override" status --env staging
x context "status with PLOYZ_ENV" env PLOYZ_ENV=fix-web "$B" status
c context "ctx (no contexts)" ctx
c context "ctx --json (no contexts)" --json ctx
c context "ctx ls (no contexts)" ctx ls
c context "ctx ls --json (no contexts)" --json ctx ls
cat >"$PLOYZ_CONFIG" <<'EOF'
current_context: prod
contexts:
  dev:
    connections:
      - unix: /tmp/dev.sock
  prod:
    connections:
      - unix: /tmp/prod.sock
      - ssh: root@203.0.113.7
EOF
c context "ctx ls" ctx ls
c context "ctx ls --json" --json ctx ls
c context "ctx" ctx
c context "ctx --json" --json ctx
m context "ctx use" ctx use dev
m context "ctx use --json" --json ctx use prod
m context "ctx use: unknown context" ctx use nope
m context "ctx use (no name, not a terminal)" ctx use
tty context "ctx use picker" "1" ctx use
tty context "ctx use picker, invalid choice" "9" ctx use
m context "ctx rm" ctx rm dev
m context "ctx rm --json" --json ctx rm prod
m context "ctx rm: unknown context" ctx rm nope
c context "ctx ls (all removed)" ctx ls
c context "status (with a context removed)" status

########## help / usage / completion ##########
c help "ployz --help" --help
c help "ployz -h" -h
c help "ployz (no args)"
c help "ployz --version" --version
c help "set --help" set --help
c help "env --help" env --help
c help "env sync -h" env sync -h
c help "project rm --help" project rm --help
c help "get -h" get -h
c help "help service add" help service add
trunc help "completion bash" 25 completion bash
c errors "completion: unknown shell" completion tcsh
c errors "missing required arg (project new)" project new
c errors "missing required arg --json (project new)" --json project new
c errors "unknown flag" get --bogus
c errors "unknown flag --json" --json get --bogus
c errors "unknown subcommand" project frobnicate
c errors "typo'd top-level command" stauts
c errors "conflicting flags (env sync --plan --close)" env sync --to --plan --close
c errors "missing positional (set --secret --from-env-file without SERVICE)" set --secret --from-env-file x
c errors "invalid enum value" env pr --bots maybe
x errors "store unreachable (bad PLOYZ_STORE)" env PLOYZ_STORE=sqlite:/nonexistent/dir/x.db "$B" project ls
x errors "store unreachable --json" env PLOYZ_STORE=sqlite:/nonexistent/dir/x.db "$B" --json project ls
x errors "bad PLOYZ_STORE scheme" env PLOYZ_STORE=postgres://x "$B" project ls
x errors "no Store, no sign-in (no PLOYZ_STORE)" env -u PLOYZ_STORE "$B" project ls
x errors "no Store, no sign-in --json" env -u PLOYZ_STORE "$B" --json project ls
x errors "cluster command against no cluster (ps)" timeout 30 "$B" ps --project shop
x errors "cluster command --json (ps)" timeout 30 "$B" --json ps --project shop
x errors "deploy without a cluster" timeout 30 "$B" deploy --project shop
x errors "service restart without a cluster" timeout 30 "$B" service restart web --project shop
x errors "logs without a cluster" timeout 30 "$B" logs web --project shop

# Captures show the per-run scratch dir as /tmp/ployz-cli-outputs-store.
FROM=$SCRATCH perl -pi -e 's/\Q$ENV{FROM}\E/\/tmp\/ployz-cli-outputs-store/g' "$CAPTURES"/*.md "$CAPTURES"/*.ansi
echo store >"$CAPTURES/.ok"
echo "store captures finished in $CAPTURES; publish with: $DOCS/publish.sh $CAPTURES"
