[package]
name = "ployz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
clap.workspace = true
ployz-telemetry.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile = "3"

[[bin]]
name = "ployz"
path = "src/main.rs"
