[package]
name = "ployz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polis = { workspace = true }
thiserror.workspace = true

[dev-dependencies]
polis = { workspace = true, features = ["test-support"] }

[features]
test-support = ["polis/test-support"]

[lints]
workspace = true
