[package]
name = "polis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
corro-api-types.workspace = true
corro-client.workspace = true
futures-util.workspace = true
iroh.workspace = true
iroh-tickets.workspace = true
irpc.workspace = true
irpc-iroh.workspace = true
libc.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time"] }
toml.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
test-support = []

[lints]
workspace = true
