[package]
name = "ployz-cert-acme-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-cert-api = { path = "../ployz-cert-api" }
ployz-store-api = { path = "../ployz-store-api" }
ployz-error = { path = "../ployz-error" }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }

[lints]
workspace = true
