[package]
name = "ployzctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "ployzctl"
path = "src/main.rs"

[dependencies]
ployz-config = { path = "../ployz-config" }
ployz-install = { path = "../ployz-install" }
clap = { workspace = true }

[lints.clippy]
indexing_slicing = "warn"
fallible_impl_from = "warn"
wildcard_enum_match_arm = "warn"
fn_params_excessive_bools = "warn"
must_use_candidate = "warn"
