[package]
name = "ployzctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ployzd = { path = "../ployzd" }
thiserror.workspace = true
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "rt"] }

[lints]
workspace = true
