[package]
name = "ployz-bpfctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "ployz-bpfctl"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
ipnet = { workspace = true }
libc = { workspace = true }
ployz-ebpf-common = { path = "../ebpf-common" }

[lints]
workspace = true
