[workspace]
members = [
    "acme",
    "acme-command",
    "bus",
    "deploy",
    "deploy-p2panda",
    "e2e",
    "environment",
    "identity",
    "iroh",
    "lease",
    "machine",
    "machine-p2panda",
    "mesh",
    "p2panda-facts",
    "p2panda-transport",
    "projection",
    "routing",
    "routing-p2panda",
    "serving",
    "volume",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.91"
version = "0.1.0"
