[package]
name = "ployz-config"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
directories = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true
