[package]
name = "ployz-config"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
directories = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
hostname = "0.4.2"
ployz-types = { path = "../ployz-types" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true
