// Generated by ployz-core. Do not edit by hand.

export type Brand<T, B extends string> = T & { readonly __brand: B };

export type SafeInteger<B extends string> = Brand<number, `safe_integer:${B}`>;

export const API_MAJOR = 1 as const;

export const KNOWN_API_FEATURES = [
  "v2.founding",
  "v2.lenses",
  "v2.join_tokens",
  "v2.machine_endpoint",
  "v2.machine_upgrade",
  "v2.machine_remove",
  "v2.join_door",
  "v2.namespace_primitives",
  "v2.deploy",
  "v2.operation_status",
  "v2.logs",
  "v2.diagnostics",
  "v2.peer_remove",
  "v2.service_remove",
  "v2.route_remove",
  "v2.route_attach",
] as const;

export type ApiFeature = KnownApiFeature | (string & {});

export type OperationInitiator = Principal;

export type AbsoluteInstallPath = string;

export type AcceptedMachineRow = { machine_id: MachineName, document: MachineDocument, };

export type AcceptedPeerRow = { peer_id: PeerName, document: PeerDocument, };

export type AcmeHttp01Document = { v: CorrosionDocumentVersion, cluster_id: ClusterName, machine_id: MachineName, hostname: RouteHostname, key_authorization: string, created_at: CorrosionTimestamp, };

export type ApiRefusal = { "kind": "unknown_source", source: string, } | { "kind": "ambiguous_source", source: string, candidate_count: number, } | { "kind": "unsupported_route" } | { "kind": "unsupported_method", method: string, } | { "kind": "missing_cluster" } | { "kind": "invalid_cluster" } | { "kind": "corrosion_unavailable", retry_after_seconds: CorrosionRetryAfterSeconds, };

export type ApiVersion = { major: number, build: string, features: Array<ApiFeature>, };

export type AutomaticHostnameMode = { "mode": "disabled" } | { "mode": "custom", suffix: RouteHostname, };

export type BuiltinWireguardKeyMismatch = { "kind": "local_public_key", machine_id: MachineName, stored: WireGuardPublicKey, local: WireGuardPublicKey, } | { "kind": "stored_ipv6_address", member_id: RosterMemberId, stored: string, derived: BuiltinWireguardMemberAddress, };

export type BuiltinWireguardMemberAddress = string;

export type CertHoldingDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, machine_id: MachineName, hostname: RouteHostname, fingerprint: Sha256Hex, issued_at: CorrosionTimestamp, expires_at: CorrosionTimestamp, };

export type ClusterDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, name: string, storage_default: StorageMode, hostname_mode: AutomaticHostnameMode, prefix: MachineEndpointSupernet, provider: MeshProvider, acme_directory_url: string, acme_contact: string | null, written_by: Principal, written_at: CorrosionTimestamp, };

export type ClusterName = Brand<string, "ClusterName">;

export type ContainerCommand = Array<string>;

export type ContainerDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName,
/**
 * Docker-owned runtime handle; it is evidence, not the Corrosion key.
 */
runtime_id: ContainerId, machine_id: MachineName, namespace_id: CorrosionNamespaceName, service_name: CorrosionServiceName,
/**
 * Stable replica identity used to authorize logs and exact retirement.
 */
replica_slot: ReplicaSlot, ip: string, deploy: DeployName, };

export type ContainerEntrypoint = "clear" | { "argv": ContainerCommand };

export type ContainerHealthcheck = { test: ContainerHealthcheckTest, interval?: HealthcheckDurationNanos | null, timeout?: HealthcheckDurationNanos | null, retries?: HealthcheckRetries | null, start_period?: HealthcheckDurationNanos | null, };

export type ContainerHealthcheckTest = "inherit" | "disable" | { "exec": ContainerCommand } | { "shell": HealthcheckShellCommand };

export type ContainerId = Brand<string, "ContainerId">;

export type ContainerIsolationDegradationReason = { "kind": "missing_control_program", path: string, } | { "kind": "missing_bytecode", path: string, } | { "kind": "missing_bpffs", path: string, } | { "kind": "missing_cgroup_v2", path: string, } | { "kind": "desired_set_too_large", desired: number, capacity: number, } | { "kind": "host_effect", message: string, };

export type ContainerIsolationTestimony = { "state": "converged", attempted_at: CorrosionTimestamp, last_successful_converge: CorrosionTimestamp, entries: number, } | { "state": "degraded", attempted_at: CorrosionTimestamp, last_successful_converge: CorrosionTimestamp | null, reason: ContainerIsolationDegradationReason, };

export type ContainerLensRow = {
/**
 * Namespace/deploy/machine/slot composite Corrosion key.
 */
id: string, document: ContainerDocument, };

export type ContainerMountPath = Brand<string, "ContainerMountPath">;

export type ContainerResourceLimits = { nano_cpus?: NanoCpus | null, memory_bytes?: MemoryBytes | null, pids?: PidsLimit | null, };

export type ContainerRuntimeSpec = { command: ContainerCommand | null, entrypoint: ContainerEntrypoint | null, environment: ServiceEnvironment, volume_mounts?: Array<ServiceVolumeMount>, healthcheck?: ContainerHealthcheck | null, cap_add?: Array<LinuxCapability>, cap_drop?: Array<LinuxCapability>, resources?: ContainerResourceLimits, };

export type CorrosionBootstrapFacts = { seed_gossip_address: string, };

export type CorrosionDeployFailure = { "kind": "routes_without_service" } | { "kind": "replicas_on_global_service" } | { "kind": "unknown_pinned_machine", machine_name: MachineName, } | { "kind": "placement", refusal: PlacementRefusal, } | { "kind": "prepare_failed", machine_id: MachineName, } | { "kind": "prepare_refused", machine_id: MachineName, } | { "kind": "prepared_replica_mismatch", machine_id: MachineName, } | { "kind": "resolved_image_mismatch" } | { "kind": "runtime_reality_unavailable" };

export type CorrosionDeployOutcome = { "kind": "completed", warnings?: Array<CorrosionDeployWarning>, } | { "kind": "failed", failure: CorrosionDeployFailure, } | { "kind": "interrupted" };

export type CorrosionDeployWarning = { "kind": "health_gate_skipped" } | { "kind": "cleanup_incomplete", machines: Array<MachineName>, };

export type CorrosionDocumentVersion = SafeInteger<"CorrosionDocumentVersion">;

export type CorrosionLogsTailLines = SafeInteger<"CorrosionLogsTailLines">;

export type CorrosionNamespaceCreateRefusal = { "kind": "already_exists", namespace_name: CorrosionNamespaceName, };

export type CorrosionNamespaceCreateReply = { namespace_name: CorrosionNamespaceName, document: NamespaceDocument, };

export type CorrosionNamespaceCreateRequest = { namespace_name: CorrosionNamespaceName, };

export type CorrosionNamespaceName = Brand<string, "CorrosionNamespaceName">;

export type CorrosionNamespaceRemoveRefusal = { "kind": "not_found", namespace_name: CorrosionNamespaceName, } | { "kind": "not_empty", namespace_name: CorrosionNamespaceName, service_names: Array<CorrosionServiceName>, route_binding_count: number, } | { "kind": "changed", namespace_name: CorrosionNamespaceName, };

export type CorrosionNamespaceRemoveReply = { "kind": "removed", namespace_name: CorrosionNamespaceName, } | { "kind": "already_absent", namespace_name: CorrosionNamespaceName, };

export type CorrosionNamespaceRemoveRequest = { namespace_name: CorrosionNamespaceName, };

export type CorrosionRetryAfterSeconds = SafeInteger<"CorrosionRetryAfterSeconds">;

export type CorrosionServiceName = Brand<string, "CorrosionServiceName">;

export type CorrosionTable = "cluster" | "machines" | "peers" | "tokens" | "namespaces" | "services" | "route_bindings" | "controller" | "containers" | "machine_status" | "gateway_observations" | "operations" | "cert_holdings" | "acme_http01";

export type CorrosionTimestamp = Brand<string, "CorrosionTimestamp">;

export type DeployAccepted = { namespace_name: CorrosionNamespaceName, deploy_name: DeployName, controller_machine_name: MachineName, };

export type DeployName = Brand<string, "DeployName">;

export type DeployRefusal = { "kind": "namespace_not_found", namespace_name: CorrosionNamespaceName, create_command: string, } | { "kind": "deploy_name_already_used", namespace_name: CorrosionNamespaceName, deploy_name: DeployName, } | { "kind": "named_volume_redeploy_unsupported" };

export type DeployRequest = { namespace_name: CorrosionNamespaceName,
/**
 * Caller-chosen namespace-scoped identity for this deploy attempt.
 */
deploy_name: DeployName, services: Array<DeployServiceRequest>, };

export type DeployServiceRequest = { service_name: CorrosionServiceName, image: ImageReference,
/**
 * A deploy-scoped pull credential. It may enter node-local workflow
 * history, but is never copied into Corrosion or operation rows.
 */
credential?: RegistryCredential | null, runtime: ContainerRuntimeSpec, health_gate: HealthGatePolicy,
/**
 * `None` inherits the incumbent row's placement, or one replica on a
 * first deploy.
 */
placement?: RequestedPlacement | null,
/**
 * `None` inherits the incumbent row's pin set unchanged.
 */
machines?: RequestedPins | null, };

export type DoctorDocument = { skipped_roster_rows: Array<DoctorSkippedRosterRow>, skipped_newer_versions: Array<DoctorSkippedNewerVersion>, versions: DoctorVersionReport, foreign_clusters: Array<DoctorForeignClusterRows>, };

export type DoctorForeignAuthorship = { "kind": "current_machine", machine: DoctorMachineIdentity, } | { "kind": "non_current_machine", machine_id: MachineName, } | { "kind": "peer", peer_id: PeerName, } | { "kind": "api_token", token_id: TokenName, } | { "kind": "unparseable" };

export type DoctorForeignClusterRows = { cluster_id: string, rows: Array<DoctorForeignRowEvidence>, };

export type DoctorForeignRowEvidence = { table: CorrosionTable, key: string, authorship: DoctorForeignAuthorship, };

export type DoctorMachineIdentity = { id: MachineName, name: MachineName, };

export type DoctorMachineVersion = { machine: DoctorMachineIdentity, version: string, };

export type DoctorMalformedRosterDocumentClass = { "kind": "missing_version" } | { "kind": "invalid_version" } | { "kind": "unsupported_version", found: number, } | { "kind": "invalid_payload" };

export type DoctorNewestVersion = { version: string, machines: Array<DoctorMachineIdentity>, };

export type DoctorRosterRowSkipReason = { "kind": "mesh_provider_mismatch", expected: MeshProvider, found: MeshProvider, } | { "kind": "malformed_document", class: DoctorMalformedRosterDocumentClass, };

export type DoctorRosterTable = "machines" | "peers";

export type DoctorSkippedNewerVersion = { table: CorrosionTable, key: string, found: number, supported: number, };

export type DoctorSkippedRosterRow = { table: DoctorRosterTable, key: string, reason: DoctorRosterRowSkipReason, };

export type DoctorVersionReport = { newest?: DoctorNewestVersion, behind: Array<DoctorMachineVersion>, invalid: Array<DoctorMachineVersion>, };

export type EbpfMeshDegradationReason = { "kind": "missing_bridge", ifname: string, } | { "kind": "host_effect", message: string, };

export type EbpfMeshDegraded = { reason: EbpfMeshDegradationReason, };

export type EnvName = Brand<string, "EnvName">;

export type EnvValue = Brand<string, "EnvValue">;

export type ExactPloyzVersion = string;

export type FoundingDriverEnrollment = { "kind": "on_host" } | { "kind": "ssh", peer_id: PeerName, document: PeerDocument, } | { "kind": "cloud", peer_id: PeerName, document: PeerDocument, };

export type FoundingRefusal = { "kind": "invalid_request", reason: FoundingValidationError, } | { "kind": "incomplete_door_material", repair_command: FoundingRepairCommand, } | { "kind": "foreign_state", requested_cluster_id: ClusterName, found_cluster_id: ClusterName, repair_command: FoundingRepairCommand, };

export type FoundingRepairCommand = "ployz machine reset";

export type FoundingRequest = { cluster_id: ClusterName, cluster: ClusterDocument, machine_id: MachineName, machine: MachineDocument, driver: FoundingDriverEnrollment, };

export type FoundingResult = { "kind": "found" } | { "kind": "resumed" } | { "kind": "no_op" };

export type FoundingRow = "cluster" | "machine" | "peer";

export type FoundingValidationError = { "kind": "cluster_key_mismatch", key: ClusterName, document_cluster_id: ClusterName, } | { "kind": "document_cluster_mismatch", row: FoundingRow, expected: ClusterName, found: ClusterName, } | { "kind": "unsupported_document_version", row: FoundingRow, found: number, } | { "kind": "unsupported_provider", found: MeshProvider, } | { "kind": "machine_transport_provider_mismatch" } | { "kind": "peer_transport_provider_mismatch" } | { "kind": "machine_address_mismatch", stored: string, derived: string, } | { "kind": "peer_address_mismatch", stored: string, derived: string, } | { "kind": "machine_subnet_not_first", expected: MachineEndpointSubnet, found: MachineEndpointSubnet, } | { "kind": "machine_lifecycle_not_active", found: MachineLifecycle, } | { "kind": "storage_default_mismatch", cluster_default: StorageMode, machine_mode: StorageMode, } | { "kind": "invalid_provenance", row: FoundingRow, expected_machine_id: MachineName, found: Principal, };

export type GatewayHttpFailure = { "failure": "proxy", message: string, };

export type GatewayObservationDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, machine_id: MachineName, observed_at: CorrosionTimestamp, listen_addr: string, serving: GatewayServingStatus, routes: Array<GatewayRouteObservation>, aggregate_failures: Array<GatewayProjectionAggregateFailure>, process_health: GatewayProcessHealth, };

export type GatewayProcessAttempt = { "status": "current", route_count: number, } | { "status": "serving_last_known_good", route_count: number, message: string, } | { "status": "failed", message: string, };

export type GatewayProcessHealth = { last_attempt: GatewayProcessAttempt | null, consecutive_failures: number, last_http_failure: GatewayHttpFailure | null, consecutive_http_failures: number, last_watch_failure: GatewayWatchFailure | null, consecutive_watch_failures: number, last_status_publish_failure: GatewayStatusPublishFailure | null, consecutive_status_publish_failures: number, };

export type GatewayProjectionAggregateFailure = { input: GatewayProjectionInputKind, rejected_rows: number, };

export type GatewayProjectionInputKind = "cluster" | "machines" | "services" | "route_bindings" | "containers";

export type GatewayRouteAvailability = { "state": "serving", upstream_count: number, } | { "state": "unavailable", reason: GatewayRouteUnavailableReason, };

export type GatewayRouteObservation = { hostname: RouteHostname, } & ({ "outcome": "applied", availability: GatewayRouteAvailability, } | { "outcome": "failed", failure: GatewayRouteProjectionFailure, });

export type GatewayRouteProjectionFailure = { "failure": "unsupported_ingress_mode", ingress_mode: IngressMode, };

export type GatewayRouteUnavailableReason = "service_missing" | "no_upstream";

export type GatewayServingStatus = "current" | "last_known_good" | "unavailable";

export type GatewayStatusPublishFailure = { "failure": "write", message: string, };

export type GatewayWatchFailure = { "failure": "open", message: string, } | { "failure": "ended", source: string, };

export type HandshakeFreshness = "healthy" | "stale";

export type HealthGatePolicy = "enforce" | "skip";

export type HealthcheckDurationNanos = SafeInteger<"HealthcheckDurationNanos">;

export type HealthcheckRetries = SafeInteger<"HealthcheckRetries">;

export type HealthcheckShellCommand = Brand<string, "HealthcheckShellCommand">;

export type HostPortBinding = { host_port: number, container_port: number, protocol: HostPortProtocol, };

export type HostPortBindings = Array<HostPortBinding>;

export type HostPortProtocol = "tcp" | "udp";

export type ImageReference = Brand<string, "ImageReference">;

export type IngressMode = "direct" | "cloudflare_tunnel" | "tailscale_funnel";

export type InstallArtifactSource = string;

export type InstallArtifactSpec = { version: InstallArtifactVersion, source: InstallArtifactSource, sha256: InstallSha256Digest, install_path: AbsoluteInstallPath, };

export type InstallArtifactVersion = string;

export type InstallSha256Digest = string;

export type JoinAdmissionAccepted = { "kind": "machine", accepted: MachineJoinAccepted, } | { "kind": "peer", accepted: PeerJoinAccepted, };

export type JoinAdmissionReply = { "outcome": "accepted", admission: JoinAdmissionAccepted, } | { "outcome": "refused", refusal: JoinDoorRefusal, };

export type JoinAdmissionRequest = { token: JoinTokenProof, member: JoinMemberRequest, };

export type JoinAdmissionValidationError = { "kind": "unsupported_provider", found: MeshProvider, } | { "kind": "endpoint_subnet_outside_cluster_prefix", subnet: MachineEndpointSubnet, } | { "kind": "endpoint_port_zero" } | { "kind": "provenance_is_not_api_token" };

export type JoinBlob = Brand<string, "JoinBlob">;

export type JoinDoorCertFingerprint = Brand<string, "JoinDoorCertFingerprint">;

export type JoinDoorCertificatePem = Brand<string, "JoinDoorCertificatePem">;

export type JoinDoorMaterial = { certificate_pem: JoinDoorCertificatePem, private_key_pem: JoinDoorPrivateKeyPem, fingerprint: JoinDoorCertFingerprint, };

export type JoinDoorPrivateKeyPem = Brand<string, "JoinDoorPrivateKeyPem">;

export type JoinDoorRefusal = { "kind": "token_not_found", token_id: TokenName, } | { "kind": "token_expired", token_id: TokenName, expires_at: CorrosionTimestamp, } | { "kind": "token_secret_mismatch", token_id: TokenName, } | { "kind": "invalid_admission", reason: JoinAdmissionValidationError, } | { "kind": "name_conflict", name: string, } | { "kind": "peer_name_conflict", name: string, } | { "kind": "identity_conflict" } | { "kind": "no_reachable_seed" } | { "kind": "endpoint_subnet_exhausted" };

export type JoinMachineSubstrate = { ployz_version: ExactPloyzVersion, corrosion_version: string, artifacts: Array<InstallArtifactSpec>, };

export type JoinMemberRequest = { "kind": "machine", request: MachineJoinRequest, } | { "kind": "peer", request: PeerJoinRequest, };

export type JoinStorageChoice = { "kind": "automatic" } | { "kind": "flag", mode: StorageMode, };

export type JoinStorageFacts = { imported_zfs_pool: boolean, total_memory_bytes: number, };

export type JoinTokenProof = { token_id: TokenName, secret: JoinTokenSecret, };

export type JoinTokenSecret = Brand<string, "JoinTokenSecret">;

export type JoinTokenTtlSeconds = SafeInteger<"JoinTokenTtlSeconds">;

export type KnownApiFeature = "v2.founding" | "v2.lenses" | "v2.join_tokens" | "v2.machine_endpoint" | "v2.machine_upgrade" | "v2.machine_remove" | "v2.join_door" | "v2.namespace_primitives" | "v2.deploy" | "v2.operation_status" | "v2.logs" | "v2.diagnostics" | "v2.peer_remove" | "v2.service_remove" | "v2.route_remove" | "v2.route_attach";

export type LensCollection = "machines" | "services" | "containers" | "machine_status" | "operations";

export type LensSnapshot = { "collection": "machines", cluster: ClusterDocument, rows: Array<MachineLensRow>, } | { "collection": "services", rows: Array<ServiceLensRow>, } | { "collection": "containers", rows: Array<ContainerLensRow>, } | { "collection": "machine_status", rows: Array<MachineStatusLensRow>, } | { "collection": "operations", rows: Array<OperationLensRow>, };

export type LensWatchEvent = { "kind": "snapshot", snapshot: LensSnapshot, } | { "kind": "state", snapshot: LensSnapshot, } | { "kind": "terminal", refusal: ApiRefusal, };

export type LinuxCapability = Brand<string, "LinuxCapability">;

export type MachineDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, name: MachineName, lifecycle: MachineLifecycle, transport: MachineTransport, storage: MachineStorageSelection, written_by: Principal, written_at: CorrosionTimestamp, };

export type MachineEndpointSetRefusal = { "kind": "not_found", machine_name: MachineName, } | { "kind": "endpoint_port_zero", machine_name: MachineName, } | { "kind": "provider_does_not_use_wireguard", machine_id: MachineName, };

export type MachineEndpointSetReply = { machine_id: MachineName, machine: MachineDocument, };

export type MachineEndpointSetRequest = { machine_name: MachineName, endpoint: string, };

export type MachineEndpointSubnet = string;

export type MachineEndpointSupernet = string;

export type MachineJoinAccepted = { cluster: ClusterDocument, machine: AcceptedMachineRow, seed: ReachableSeedMachine, door: JoinDoorMaterial, corrosion: CorrosionBootstrapFacts, substrate: JoinMachineSubstrate, };

export type MachineJoinRequest = { name: MachineName, public_key: WireGuardPublicKey, endpoint: string | null, storage_choice: JoinStorageChoice, storage_facts: JoinStorageFacts, };

export type MachineLensRow = { id: MachineName, document: MachineDocument, };

export type MachineLifecycle = "active" | "draining";

export type MachineLoadBand = "idle" | "normal" | "hot";

export type MachineName = Brand<string, "MachineName">;

export type MachineRemoveRefusal = { "kind": "not_found", machine_name: MachineName, };

export type MachineRemoveReply = { "kind": "removed", machine_name: MachineName, };

export type MachineRemoveRequest = { machine_name: MachineName, };

export type MachineStatusDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, machine_id: MachineName, ployz_version: string, corrosion_version: string, architecture: string, free_disk_bytes: number, free_memory_bytes: number, load: MachineLoadBand, observed_at: CorrosionTimestamp,
/**
 * `None` denotes an additive v1 status document without mesh testimony.
 * Keeper mesh status writes populate this field.
 */
mesh?: MeshConvergenceTestimony | null,
/**
 * `None` denotes a status document written before isolation testimony.
 */
container_isolation?: ContainerIsolationTestimony | null,
/**
 * `None` denotes a row written before live peer-handshake testimony existed.
 * A current writer publishes `Some`, including an empty map on a one-machine roster.
 */
wireguard_handshakes?: { [key in MachineName]: WireGuardHandshakeEvidence } | null, };

export type MachineStatusLensRow = { id: MachineName, document: MachineStatusDocument, };

export type MachineStorageIneligibleReason = "low_ram";

export type MachineStorageSelection = { mode: StorageMode, reason: MachineStorageSelectionReason, };

export type MachineStorageSelectionReason = { "kind": "default" } | { "kind": "flag" } | { "kind": "ineligible", reason: MachineStorageIneligibleReason, };

export type MachineTransport = { "kind": "wireguard", pubkey: WireGuardPublicKey, addr_v6: string, endpoint: string | null, subnet_v4: MachineEndpointSubnet, } | { "kind": "tailscale", ip: string, subnet_v4: MachineEndpointSubnet, };

export type MachineUpgradeRefusal = { "kind": "unsupported_supervisor", supervisor: MachineUpgradeSupervisor, } | { "kind": "download_failed", message: string, } | { "kind": "sha256_mismatch", expected: InstallSha256Digest, got: InstallSha256Digest, } | { "kind": "staging_failed", message: string, } | { "kind": "keeper_refused", message: string, };

export type MachineUpgradeReply = { version: InstallArtifactVersion, sha256: InstallSha256Digest, };

export type MachineUpgradeRequest = { version: InstallArtifactVersion, sha256: InstallSha256Digest, url: MachineUpgradeUrl, };

export type MachineUpgradeSupervisor = "systemd" | "open_rc";

export type MachineUpgradeUrl = string;

export type MemoryBytes = SafeInteger<"MemoryBytes">;

export type MeshComponentDegraded = { message: string, };

export type MeshComponentNotAttempted = { reason: MeshNotAttemptedReason, };

export type MeshComponentReady = { converged_at: CorrosionTimestamp, };

export type MeshConvergenceTestimony = { "state": "no_roster", attempted_at: CorrosionTimestamp, } | { "state": "key_mismatch", attempted_at: CorrosionTimestamp, mismatches: Array<BuiltinWireguardKeyMismatch>, } | { "state": "converged", bind_address: BuiltinWireguardMemberAddress, attempted_at: CorrosionTimestamp, last_successful_converge: CorrosionTimestamp, wireguard: MeshComponentReady, ebpf: MeshComponentReady, } | { "state": "degraded", bind_address: BuiltinWireguardMemberAddress, attempted_at: CorrosionTimestamp, last_successful_converge: CorrosionTimestamp | null, degradation: MeshDegradation, };

export type MeshDegradation = { "components": "wireguard", wireguard: MeshComponentDegraded, ebpf: MeshComponentNotAttempted, } | { "components": "ebpf", wireguard: MeshComponentReady, ebpf: EbpfMeshDegraded, };

export type MeshNotAttemptedReason = "dependency_degraded";

export type MeshProvider = "builtin_wireguard" | "tailscale";

export type NamedRemovalOutcome = "removed" | "already_absent";

export type NamespaceDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, name: CorrosionNamespaceName, written_by: Principal, written_at: CorrosionTimestamp, };

export type NanoCpus = SafeInteger<"NanoCpus">;

export type OperationDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, machine_id: MachineName, initiator: Principal, namespace_id: CorrosionNamespaceName, deploy_name: DeployName, created_at: CorrosionTimestamp, } & ({ "state": "created" } | { "state": "terminal", completed_at: CorrosionTimestamp, outcome: CorrosionDeployOutcome, });

export type OperationLensRow = { namespace_name: CorrosionNamespaceName, deploy_name: DeployName, document: OperationDocument, };

export type PeerDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, name: PeerName, transport: PeerTransport, written_by: Principal, written_at: CorrosionTimestamp, };

export type PeerJoinAccepted = { cluster: ClusterDocument, peer: AcceptedPeerRow, seed: ReachableSeedMachine, corrosion: CorrosionBootstrapFacts, };

export type PeerJoinRequest = { name: PeerName, public_key: WireGuardPublicKey, endpoint: string | null, };

export type PeerName = Brand<string, "PeerName">;

export type PeerRemoveRefusal = { "kind": "not_found", peer_name: PeerName, } | { "kind": "stored_row_unselectable", peer_name: PeerName, } | { "kind": "concurrent_mutation", peer_name: PeerName, };

export type PeerRemoveReply = { peer_name: PeerName, outcome: NamedRemovalOutcome, };

export type PeerRemoveRequest = { peer_name: PeerName, };

export type PeerTransport = { "kind": "wireguard", pubkey: WireGuardPublicKey, addr_v6: string, endpoint: string | null, } | { "kind": "tailscale", ip: string, };

export type PidsLimit = SafeInteger<"PidsLimit">;

export type PinnedMachineNames = Array<MachineName>;

export type PlacementElimination = { machine_id: MachineName, machine_name: MachineName, reason: PlacementEliminationReason, };

export type PlacementEliminationReason = { "kind": "draining" } | { "kind": "free_disk_below_floor", free_disk_bytes: number, } | { "kind": "outside_pin_set" };

export type PlacementRefusal = { "kind": "no_eligible_machines", eliminations: Array<PlacementElimination>, } | { "kind": "volume_replica_limit", requested: ServiceReplicaCount, };

export type Principal = { "kind": "machine", machine_id: MachineName, } | { "kind": "peer", peer_id: PeerName, } | { "kind": "api_token", token_id: TokenName, };

export type ReachableSeedMachine = { machine_id: MachineName, transport: MachineTransport, };

export type RegistryCredential = { "kind": "basic", username: RegistryCredentialUsername, password: RegistryCredentialSecret, } | { "kind": "identity_token", token: RegistryCredentialSecret, };

export type RegistryCredentialSecret = string;

export type RegistryCredentialUsername = string;

export type ReplicaSlot = { "kind": "replicated", number: ReplicatedReplicaSlot, } | { "kind": "global" };

export type ReplicatedReplicaSlot = SafeInteger<"ReplicatedReplicaSlot">;

export type RequestedPins = { "kind": "machines", names: PinnedMachineNames, } | { "kind": "any" };

export type RequestedPlacement = { "mode": "replicas", replicas: ServiceReplicaCount, } | { "mode": "replicated", replicas?: ServiceReplicaCount | null, } | { "mode": "global", host_ports?: HostPortBindings, };

export type RosterMemberId = { "kind": "machine", machine_id: MachineName, } | { "kind": "peer", peer_id: PeerName, };

export type RouteAttachOutcome = "attached" | "already_attached";

export type RouteAttachRefusal = { "kind": "unsupported_ingress_mode", requested: IngressMode, } | { "kind": "namespace_not_found", namespace_name: CorrosionNamespaceName, } | { "kind": "namespace_stored_row_unselectable", namespace_name: CorrosionNamespaceName, } | { "kind": "service_not_found", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, } | { "kind": "service_stored_row_unselectable", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, } | { "kind": "hostname_already_attached", hostname: RouteHostname, remove: RouteRemoveRequest, };

export type RouteAttachReply = { outcome: RouteAttachOutcome, };

export type RouteAttachRequest = { hostname: RouteHostname, namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, endpoint_port: RoutePort, ingress_mode: IngressMode, };

export type RouteBindingDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, hostname: RouteHostname, namespace_id: CorrosionNamespaceName, service_name: CorrosionServiceName, endpoint_port: RoutePort, origin: RouteBindingOrigin, ingress_mode: IngressMode, written_by: Principal, written_at: CorrosionTimestamp, };

export type RouteBindingOrigin = "declared" | "automatic";

export type RouteHostname = Brand<string, "RouteHostname">;

export type RoutePort = SafeInteger<"RoutePort">;

export type RouteRemoveRefusal = { "kind": "not_found", hostname: RouteHostname, } | { "kind": "stored_row_unselectable", hostname: RouteHostname, } | { "kind": "concurrent_mutation", hostname: RouteHostname, };

export type RouteRemoveReply = { hostname: RouteHostname, outcome: NamedRemovalOutcome, };

export type RouteRemoveRequest = { hostname: RouteHostname, };

export type ServiceDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, namespace_id: CorrosionNamespaceName, name: CorrosionServiceName, image: ImageReference, env_fingerprints: { [key in string]: Sha256Hex }, pinned_machines: Array<MachineName>, active_deploy: DeployName, previous_image: ImageReference | null, deployed_at: CorrosionTimestamp, written_by: Principal, written_at: CorrosionTimestamp, } & ({ "mode": "replicated", replicas: ServiceReplicaCount, } | { "mode": "global",
/**
 * Host-published ports; an absent field reads as none published.
 */
host_ports?: HostPortBindings, });

export type ServiceEnvironment = Record<EnvName, EnvValue>;

export type ServiceLensRow = { key: string, document: ServiceDocument, };

export type ServiceLogLine = { stream: ServiceLogStream, line: string, };

export type ServiceLogStream = "stdout" | "stderr";

export type ServiceLogsFollowEvent = { "kind": "line", log: ServiceLogLine, } | { "kind": "gap" } | { "kind": "terminal", refusal: ServiceLogsRefusal, };

export type ServiceLogsRefusal = { "kind": "service_not_found", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, } | { "kind": "container_not_found", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, } | { "kind": "unmanaged_container", container_id: ContainerId, } | { "kind": "machine_selector_required", machines: Array<MachineName>, } | { "kind": "hosting_machines_unresolved", machine_ids: Array<MachineName>, } | { "kind": "remote_owner", machine_id: MachineName,
/**
 * `None` when the owning machine's roster row is no longer readable.
 */
machine_name?: MachineName | null, } | { "kind": "runtime_unavailable", machine_id: MachineName, };

export type ServiceLogsRequest = { tail_lines?: CorrosionLogsTailLines | null,
/**
 * Selects the replica hosted by the named machine when the service runs
 * containers on more than one machine.
 */
machine?: MachineName | null, };

export type ServiceLogsTailReply = { lines: Array<ServiceLogLine>, truncated: boolean, };

export type ServiceRemoveRowRefusal = { "kind": "not_found", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, } | { "kind": "stored_row_unselectable", key: string, } | { "kind": "concurrent_mutation", namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, };

export type ServiceRemoveRowReply = { namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, outcome: NamedRemovalOutcome, };

export type ServiceRemoveRowRequest = { namespace_name: CorrosionNamespaceName, service_name: CorrosionServiceName, };

export type ServiceReplicaCount = SafeInteger<"ServiceReplicaCount">;

export type ServiceVolumeMount = { volume_name: VolumeName, target: ContainerMountPath, };

export type Sha256Hex = Brand<string, "Sha256Hex">;

export type StatusAnsweringMachine = { "state": "known", id: MachineName, name: MachineName, } | { "state": "unknown", id: MachineName, };

export type StatusBarrier = "ready" | "catching_up" | "no_roster";

export type StatusClusterSummary = { id: ClusterName, name: string, machine_count: number, };

export type StatusDegradationReason = "corrosion_unavailable" | "invalid_corrosion_health_response";

export type StatusDocument = { cluster?: StatusClusterSummary, answering_machine: StatusAnsweringMachine, sync: StatusSync, barrier: StatusBarrier, machines: Array<StatusMachineRow>, hints: Array<StatusHint>, };

export type StatusHandshakeEvidence = { "state": "self_machine" } | { "state": "no_testimony" } | { "state": "never" } | { "state": "ago", seconds: number, freshness: HandshakeFreshness, };

export type StatusHint = "all_peer_handshakes_stale";

export type StatusMachineRow = { id: MachineName, name: MachineName, address: string, handshake: StatusHandshakeEvidence, };

export type StatusSync = { "state": "caught_up", p99_lag: number, } | { "state": "syncing", gaps: number, queue_size: number, p99_lag: number, } | { "state": "no_lag_sample" } | { "state": "degraded", reason: StatusDegradationReason, };

export type StorageMode = "plain" | "zfs";

export type TokenCreateRefusal = { "kind": "no_advertised_door_endpoint", repair_command: string, } | { "kind": "too_many_advertised_door_endpoints", found: number, maximum: number, };

export type TokenCreateReply = { token_id: TokenName, blob: JoinBlob, created_at: CorrosionTimestamp, expires_at: CorrosionTimestamp, };

export type TokenCreateRequest = { name: TokenName, ttl_seconds: JoinTokenTtlSeconds, };

export type TokenDocument = { v: CorrosionDocumentVersion, cluster_id: ClusterName, secret_sha256: Sha256Hex, created_at: CorrosionTimestamp, expires_at: CorrosionTimestamp, written_by: Principal, written_at: CorrosionTimestamp, };

export type TokenListItem = { token_id: TokenName, created_at: CorrosionTimestamp, expires_at: CorrosionTimestamp, };

export type TokenListReply = { tokens: Array<TokenListItem>, };

export type TokenListRequest = { scope: TokenListScope, };

export type TokenListScope = "live" | "all";

export type TokenName = Brand<string, "TokenName">;

export type TokenRevokeRefusal = { "kind": "not_found", token_id: TokenName, };

export type TokenRevokeReply = { token_id: TokenName, };

export type TokenRevokeRequest = { token_id: TokenName, };

export type VolumeName = Brand<string, "VolumeName">;

export type WireGuardHandshakeEvidence = { "state": "never" } | { "state": "at", unix_seconds: number, };

export type WireGuardPublicKey = string;
