// Generated by ployz-sdk-types. Do not edit by hand.

export type Brand<T, B extends string> = T & { readonly __brand: B };

export type SafeInteger<B extends string> = Brand<number, `safe_integer:${B}`>;

export const MAX_OPERATION_EVENT_REPLAY_LIMIT = 512 as const;

export type OperationId = Brand<string, "OperationId">;

export type OperationOwnerId = Brand<string, "OperationOwnerId">;

export type OperationIdempotencyKey = Brand<string, "OperationIdempotencyKey">;

export type EventSequence = Brand<string, "EventSequence">;

export type ServiceId = Brand<string, "ServiceId">;

export type RevisionId = Brand<string, "RevisionId">;

export type NodeId = Brand<string, "NodeId">;

export type ContainerId = Brand<string, "ContainerId">;

export type CertId = Brand<string, "CertId">;

export type MachineName = Brand<string, "MachineName">;

export type JoinTokenFingerprint = Brand<string, "JoinTokenFingerprint">;

export type JoinTokenExpiresAt = Brand<string, "JoinTokenExpiresAt">;

export type JoinTokenRedeemedAt = Brand<string, "JoinTokenRedeemedAt">;

export type IssuedJoinToken = { fingerprint: JoinTokenFingerprint, expires_at: JoinTokenExpiresAt, };

export type MachineBootstrapUrl = Brand<string, "MachineBootstrapUrl">;

export type MachineJoinToken = Brand<string, "MachineJoinToken">;

export type ImageReference = Brand<string, "ImageReference">;

export type ReplicaCount = SafeInteger<"ReplicaCount">;

export type ReplicaSlot = SafeInteger<"ReplicaSlot">;

export type DeployRequest = { service_id: ServiceId, target_revision: RevisionId, image: ImageReference, replicas: ReplicaCount, };

export type DeployPlan = { service_id: ServiceId, target_revision: RevisionId, steps: Array<DeployPlanStep>, };

export type DeployPlanStep = { "step": "use_existing_container", node_id: NodeId, container_id: ContainerId, slot: ReplicaSlot, } | { "step": "run_container", node_id: NodeId, slot: ReplicaSlot, };

export type OperationLeaseExpiresAt = Brand<string, "OperationLeaseExpiresAt">;

export type OperationOwnerLease = { operation_id: OperationId, owner_id: OperationOwnerId, expires_at: OperationLeaseExpiresAt, };

export type OperationEventReplayLimit = SafeInteger<"OperationEventReplayLimit">;

export type OperationEventReplayRequest = { operation_id: OperationId, start_sequence: EventSequence, limit: OperationEventReplayLimit, };

export type OperationEventReplayPage = { events: Array<ReplayedOperationEvent>, cursor: OperationEventReplayCursor, };

export type OperationEventReplayCursor = { "state": "caught_up" } | { "state": "terminal" } | { "state": "more", next_start_sequence: EventSequence, };

export type ReplayedOperationEvent = { sequence: EventSequence, event: OperationEvent, };

export type OperationStatus = { "kind": "deploy", id: OperationId, service_id: ServiceId, state: DeployOperationState, last_event_sequence: EventSequence, } | { "kind": "cert", id: OperationId, cert_id: CertId, state: CertOperationState, last_event_sequence: EventSequence, } | { "kind": "machine_add", id: OperationId, node_id: NodeId, name: MachineName, gateway: FirstNodeGateway, state: MachineAddOperationState, last_event_sequence: EventSequence, };

export type OperationStatusSnapshot = { status: OperationStatus, ownership: OperationOwnershipStatus, };

export type OperationOwnershipStatus = { "state": "unclaimed" } | { "state": "owned", lease: OperationOwnerLease, } | { "state": "expired", lease: OperationOwnerLease, };

export type OperationSubject = { "kind": "deploy", service_id: ServiceId, } | { "kind": "cert", cert_id: CertId, } | { "kind": "machine_add", node_id: NodeId, } | { "kind": "machine_drain", node_id: NodeId, } | { "kind": "service_remove", service_id: ServiceId, };

export type MachineAddOperationState = { "state": "pending", join_token: IssuedJoinToken, } | { "state": "joining", joined_at: JoinTokenRedeemedAt, } | { "state": "completed" } | { "state": "failed", failure: MachineAddFailure, } | { "state": "cancelled", reason: CancellationReason, };

export type MachineAddOperationStateName = "pending" | "joining" | "completed" | "failed" | "cancelled";

export type MachineAddFailure = { "kind": "invalid_join_token" } | { "kind": "join_token_expired", expired_at: JoinTokenExpiresAt, } | { "kind": "bootstrap_failed", message: FailureMessage, } | { "kind": "readiness_failed", evidence: MachineReadinessEvidence, };

export type MachineReadinessEvidence = { nats_tunnel: MachineReadinessCheck, heartbeat: MachineReadinessCheck, node_inspect: MachineReadinessCheck, };

export type MachineReadinessCheck = { "state": "confirmed" } | { "state": "missing", reason: FailureMessage, };

export type FirstNodeGateway = "install" | "skip";

export type DeployOperationState = { "state": "accepted" } | { "state": "planning" } | { "state": "running", stage: DeployRunningStage, } | { "state": "completed" } | { "state": "failed", failure: DeployOperationFailure, } | { "state": "cancelled", reason: CancellationReason, };

export type DeployRunningStage = "preparing_wireguard_ebpf" | "starting_containers" | "waiting_for_health" | "active_service_commit";

export type CertOperationState = { "state": "accepted" } | { "state": "running", stage: CertRunningStage, } | { "state": "completed" } | { "state": "failed", failure: CertOperationFailure, } | { "state": "cancelled", reason: CancellationReason, };

export type CertRunningStage = "challenge_published" | "validation_started";

export type OperationEvent = { "event": "deploy_submitted", operation_id: OperationId, target: DeployRequest, } | { "event": "deploy_planning_started", operation_id: OperationId, } | { "event": "deploy_plan_created", operation_id: OperationId, plan: DeployPlan, } | { "event": "deploy_running", operation_id: OperationId, stage: DeployRunningStage, } | { "event": "deploy_container_started", operation_id: OperationId, node_id: NodeId, container_id: ContainerId, } | { "event": "deploy_health_check_started", operation_id: OperationId, } | { "event": "deploy_completed", operation_id: OperationId, } | { "event": "deploy_failed", operation_id: OperationId, failure: DeployOperationFailure, } | { "event": "cert_renewal_submitted", operation_id: OperationId, cert_id: CertId, } | { "event": "cert_challenge_published", operation_id: OperationId, cert_id: CertId, challenge: AcmeHttp01Challenge, } | { "event": "cert_validation_started", operation_id: OperationId, cert_id: CertId, } | { "event": "cert_completed", operation_id: OperationId, active_cert: ActiveCertState, } | { "event": "cert_failed", operation_id: OperationId, failure: CertOperationFailure, } | { "event": "machine_add_submitted", operation_id: OperationId, node_id: NodeId, name: MachineName, gateway: FirstNodeGateway, join_token: IssuedJoinToken, } | { "event": "machine_add_joined", operation_id: OperationId, node_id: NodeId, joined_at: JoinTokenRedeemedAt, } | { "event": "machine_add_completed", operation_id: OperationId, node_id: NodeId, } | { "event": "machine_add_failed", operation_id: OperationId, node_id: NodeId, failure: MachineAddFailure, } | { "event": "cancelled", operation_id: OperationId, reason: CancellationReason, };

export type FailureMessage = Brand<string, "FailureMessage">;

export type CancellationReason = Brand<string, "CancellationReason">;

export type RouteHostname = Brand<string, "RouteHostname">;

export type RoutePort = SafeInteger<"RoutePort">;

export type RouteTarget = { hostname: RouteHostname, port: RoutePort, };

export type RetainedArtifact = { "type": "started_container", node_id: NodeId, container_id: ContainerId, log_hint: OperatorHint, };

export type HealthCheckFailure = { "reason": "probe_failed", node_id: NodeId, container_id: ContainerId, message: FailureMessage, log_hint: OperatorHint, } | { "reason": "timed_out", timeout_seconds: number, };

export type WireGuardEbpfComponent = "wireguard" | "ebpf_forwarding";

export type ActiveServiceCommitFailure = { "reason": "active_service_changed", expected_current: ExpectedActiveService, current_revision: RevisionId | null, attempted_revision: RevisionId, };

export type ArtifactUnavailableReason = { "reason": "bundle_missing" } | { "reason": "bundle_unreadable", message: FailureMessage, };

export type RouteCutoverFailureReason = { "reason": "gateway_unavailable", node_id: NodeId, } | { "reason": "route_rejected", message: FailureMessage, } | { "reason": "timed_out", timeout_seconds: number, };

export type DeployOperationFailure = { "kind": "planning_failed", service_id: ServiceId, revision_id: RevisionId, message: FailureMessage, } | { "kind": "artifact_unavailable", service_id: ServiceId, revision_id: RevisionId, reason: ArtifactUnavailableReason, } | { "kind": "wireguard_ebpf_unavailable", node_id: NodeId, component: WireGuardEbpfComponent, message: FailureMessage, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "wireguard_ebpf_preparation_timed_out", nodes: Array<NodeId>, timeout_seconds: number, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "runtime_unavailable", node_id: NodeId, message: FailureMessage, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "health_check_failed", health_check: HealthCheckFailure, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "control_plane_commit_failed", service_id: ServiceId, revision_id: RevisionId, message: FailureMessage, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "active_service_commit_rejected", service_id: ServiceId, revision_id: RevisionId, reason: ActiveServiceCommitFailure, retained_artifacts: Array<RetainedArtifact>, } | { "kind": "route_cutover_failed", route: RouteTarget, reason: RouteCutoverFailureReason, retained_artifacts: Array<RetainedArtifact>, };

export type CertOperationFailure = { "kind": "challenge_publish_failed", cert_id: CertId, message: FailureMessage, } | { "kind": "acme_validation_failed", cert_id: CertId, message: FailureMessage, retained_active_cert: ActiveCertState | null, } | { "kind": "active_cert_commit_failed", cert_id: CertId, bundle_ref: CertBundleRef, validity: CertValidityWindow, message: FailureMessage, retained_active_cert: ActiveCertState | null, };

export type OperatorHint = Brand<string, "OperatorHint">;

export type CertValidAt = Brand<string, "CertValidAt">;

export type CertValidityWindow = { not_before: CertValidAt, not_after: CertValidAt, };

export type CertBundleRef = Brand<string, "CertBundleRef">;

export type AcmeChallengeToken = Brand<string, "AcmeChallengeToken">;

export type AcmeChallengeValue = Brand<string, "AcmeChallengeValue">;

export type AcmeChallengeTtlSeconds = Brand<string, "AcmeChallengeTtlSeconds">;

export type AcmeHttp01Challenge = { hostname: RouteHostname, token: AcmeChallengeToken, value: AcmeChallengeValue, ttl_seconds: AcmeChallengeTtlSeconds, };

export type ActiveCertState = { cert_id: CertId, hostname: RouteHostname, bundle_ref: CertBundleRef, validity: CertValidityWindow, };

export type ExpectedActiveService = "absent" | { "revision": RevisionId };

export type ActiveServiceState = { service_id: ServiceId, active_revision: RevisionId, };

export type ActiveServiceCommitRequest = { service_id: ServiceId, expected_current: ExpectedActiveService, target_revision: RevisionId, };

export type DeploySubmitRequest = { operation_id: OperationId, idempotency_key: OperationIdempotencyKey, target: DeployRequest, };

export type MachineAddRequest = { operation_id: OperationId, idempotency_key: OperationIdempotencyKey, node_id: NodeId, name: MachineName, gateway: MachineAddGateway, join_bundle: MachineJoinBundle, };

export type MachineAddGateway = "install" | "skip";

export type MachineAddAccepted = { accepted: AcceptedOperation, node_id: NodeId, bootstrap_url: MachineBootstrapUrl, join_token: MachineJoinToken, };

export type MachineJoinClusterName = string;

export type InstallArtifactVersion = string;

export type InstallArtifactSource = string;

export type InstallSha256Digest = string;

export type AbsoluteInstallPath = string;

export type MachineJoinBundle = { cluster_name: MachineJoinClusterName, ployzd: MachineJoinPloyzdArtifact, };

export type MachineJoinPloyzdArtifact = { version: InstallArtifactVersion, source: InstallArtifactSource, sha256: InstallSha256Digest, install_path: AbsoluteInstallPath, };

export type MachineJoinRedeemRequest = { join_token: MachineJoinToken, };

export type MachineJoinRedeemed = { operation_id: OperationId, node_id: NodeId, name: MachineName, gateway: FirstNodeGateway, join_bundle: MachineJoinBundle, joined_at: JoinTokenRedeemedAt, last_event_sequence: EventSequence, result: MachineJoinRedeemResult, };

export type MachineJoinRedeemResult = "joined" | "already_joined";

export type MachineJoinRedeemError = { "error": "invalid_join_token" } | { "error": "unknown_join_token" } | { "error": "rejected", operation_id: OperationId, failure: MachineAddFailure, } | { "error": "operation_not_pending", operation_id: OperationId, current: MachineAddOperationStateName, } | { "error": "unavailable", source: MachineJoinRedeemUnavailableSource, };

export type MachineJoinRedeemUnavailableSource = { "source": "status_read", failure: StatusReadFailure, } | { "source": "status_write", failure: OperationSubmitStatusFailure, } | { "source": "event_log", failure: OperationSubmitEventFailure, } | { "source": "clock", failure: OperationSubmitClockFailure, } | { "source": "operation_corrupt" };

export type MachineJoinReportRequest = { join_token: MachineJoinToken, outcome: MachineJoinReportOutcome, };

export type MachineJoinReportOutcome = { "outcome": "completed" } | { "outcome": "failed", failure: MachineJoinReportFailure, };

export type MachineJoinReportFailure = { "kind": "bootstrap_failed", message: FailureMessage, };

export type MachineJoinReported = { operation_id: OperationId, node_id: NodeId, last_event_sequence: EventSequence, outcome: MachineJoinReportOutcome, };

export type MachineJoinReportError = { "error": "invalid_join_token" } | { "error": "unknown_join_token" } | { "error": "operation_not_joining", operation_id: OperationId, current: MachineAddOperationStateName, } | { "error": "unavailable", source: MachineJoinReportUnavailableSource, };

export type MachineJoinReportUnavailableSource = { "source": "status_read", failure: StatusReadFailure, } | { "source": "status_write", failure: OperationSubmitStatusFailure, } | { "source": "event_log", failure: OperationSubmitEventFailure, } | { "source": "operation_corrupt" };

export type OpsStatusRequest = { operation_id: OperationId, };

export type AcceptedOperation = { operation_id: OperationId, watch_subject: string, start_sequence: EventSequence, owner_lease: OperationOwnerLease, };

export type OperationApiResponse<T, E> = { "status": "ok", value: T, } | { "status": "domain_error", error: E, };

export type DeploySubmitError = { "error": "unavailable", operation_id: OperationId, source: DeploySubmitUnavailableSource, } | { "error": "duplicate_sequence_mismatch", operation_id: OperationId, sequence: EventSequence, };

export type DeploySubmitUnavailableSource = { "source": "status_store", failure: OperationSubmitStatusFailure, } | { "source": "event_log", failure: OperationSubmitEventFailure, } | { "source": "clock", failure: OperationSubmitClockFailure, };

export type OperationSubmitStatusFailure = "open_bucket" | "encode_status" | "decode_status" | "encode_submission" | "decode_submission" | "encode_lease" | "decode_lease" | "cas_conflict" | "get_status" | "clock" | "timeout";

export type OperationSubmitEventFailure = "encode_event" | "decode_event" | "publish_request" | "publish_ack" | "read_event" | "timeout" | "invalid_ack_sequence";

export type OperationSubmitClockFailure = "before_unix_epoch";

export type MachineAddError = { "error": "unavailable", operation_id: OperationId, source: MachineAddUnavailableSource, } | { "error": "duplicate_sequence_mismatch", operation_id: OperationId, sequence: EventSequence, };

export type MachineAddUnavailableSource = { "source": "status_store", failure: OperationSubmitStatusFailure, } | { "source": "event_log", failure: OperationSubmitEventFailure, } | { "source": "clock", failure: OperationSubmitClockFailure, } | { "source": "bootstrap_material", failure: BootstrapMaterialFailure, };

export type BootstrapMaterialFailure = "encode_join_bundle" | "issue_join_token" | "render_bootstrap_url";

export type OpsStatusError = { "error": "no_such_operation", operation_id: OperationId, } | { "error": "unavailable", operation_id: OperationId, source: OpsStatusUnavailableSource, };

export type OpsStatusUnavailableSource = { "source": "status_store", failure: StatusReadFailure, };

export type StatusReadFailure = "decode_status" | "decode_lease" | "get_status" | "clock" | "timeout";

export type OpsWatchError = { "error": "no_such_operation", operation_id: OperationId, } | { "error": "unavailable", operation_id: OperationId, source: OpsWatchUnavailableSource, };

export type OpsWatchUnavailableSource = { "source": "status_store", failure: StatusReadFailure, } | { "source": "event_log", failure: EventReplayFailure, };

export type EventReplayFailure = "decode_event" | "read_event" | "timeout" | "invalid_event_sequence" | "invalid_next_replay_sequence";

export type DeploySubmitResponse = OperationApiResponse<AcceptedOperation, DeploySubmitError>;

export type MachineAddResponse = OperationApiResponse<MachineAddAccepted, MachineAddError>;

export type MachineJoinRedeemResponse = OperationApiResponse<MachineJoinRedeemed, MachineJoinRedeemError>;

export type MachineJoinReportResponse = OperationApiResponse<MachineJoinReported, MachineJoinReportError>;

export type OpsStatusResponse = OperationApiResponse<OperationStatusSnapshot, OpsStatusError>;

export type OpsWatchRequest = OperationEventReplayRequest;

export type OpsWatchResponse = OperationApiResponse<OperationEventReplayPage, OpsWatchError>;

export const OPERATION_API_CONTRACTS = [
  { name: "deploy.submit", subject: "plz.v1.svc.api.deploy.submit", execution: "accepts_operation", request: "DeploySubmitRequest", success: "AcceptedOperation", error: "DeploySubmitError", response: "DeploySubmitResponse" },
  { name: "machine.add", subject: "plz.v1.svc.api.machine.add", execution: "accepts_operation", request: "MachineAddRequest", success: "MachineAddAccepted", error: "MachineAddError", response: "MachineAddResponse" },
  { name: "machine.join.redeem", subject: "plz.v1.svc.api.machine.join.redeem", execution: "mutates_operation", request: "MachineJoinRedeemRequest", success: "MachineJoinRedeemed", error: "MachineJoinRedeemError", response: "MachineJoinRedeemResponse" },
  { name: "machine.join.report", subject: "plz.v1.svc.api.machine.join.report", execution: "mutates_operation", request: "MachineJoinReportRequest", success: "MachineJoinReported", error: "MachineJoinReportError", response: "MachineJoinReportResponse" },
  { name: "ops.status", subject: "plz.v1.svc.api.ops.status", execution: "query", request: "OpsStatusRequest", success: "OperationStatusSnapshot", error: "OpsStatusError", response: "OpsStatusResponse" },
  { name: "ops.watch", subject: "plz.v1.svc.api.ops.watch", execution: "query", request: "OpsWatchRequest", success: "OperationEventReplayPage", error: "OpsWatchError", response: "OpsWatchResponse" },
] as const;
