[package]
name = "ployz-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ployz-api = { path = "../ployz-api" }
ployz-config = { path = "../ployz-config" }
ployz-types = { path = "../ployz-types" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "net", "io-util", "process"] }

[lints]
workspace = true
