//! TypeScript contract export owned by the Rust SDK type crate.

use crate::operation_api::OperationApiContract;
use crate::{
    AbsoluteInstallPath, AcceptedOperation, AcmeChallengeToken, AcmeChallengeTtlSeconds,
    AcmeChallengeValue, AcmeHttp01Challenge, ActiveCertState, ActiveServiceCommitFailure,
    ActiveServiceCommitRequest, ActiveServiceState, ArtifactUnavailableReason,
    BootstrapMaterialFailure, CancellationReason, CertBundleRef, CertId, CertOperationFailure,
    CertOperationState, CertRunningStage, CertValidAt, CertValidityWindow, ContainerId,
    DeployOperationFailure, DeployOperationState, DeployPlan, DeployPlanStep, DeployRequest,
    DeployRunningStage, DeploySubmitError, DeploySubmitRequest, DeploySubmitUnavailableSource,
    EventReplayFailure, EventSequence, ExpectedActiveService, FailureMessage, FirstNodeGateway,
    HealthCheckFailure, ImageReference, InstallArtifactSource, InstallArtifactVersion,
    InstallSha256Digest, IssuedJoinToken, JoinTokenExpiresAt, JoinTokenFingerprint,
    JoinTokenRedeemedAt, MAX_OPERATION_EVENT_REPLAY_LIMIT, MachineAddAccepted, MachineAddError,
    MachineAddFailure, MachineAddGateway, MachineAddOperationState, MachineAddOperationStateName,
    MachineAddRequest, MachineAddUnavailableSource, MachineBootstrapUrl, MachineJoinBundle,
    MachineJoinClusterName, MachineJoinPloyzdArtifact, MachineJoinRedeemError,
    MachineJoinRedeemRequest, MachineJoinRedeemResult, MachineJoinRedeemUnavailableSource,
    MachineJoinRedeemed, MachineJoinReportError, MachineJoinReportFailure,
    MachineJoinReportOutcome, MachineJoinReportRequest, MachineJoinReportUnavailableSource,
    MachineJoinReported, MachineJoinToken, MachineName, MachineReadinessCheck,
    MachineReadinessEvidence, NodeId, OperationApiResponse, OperationEvent,
    OperationEventReplayCursor, OperationEventReplayLimit, OperationEventReplayPage,
    OperationEventReplayRequest, OperationId, OperationIdempotencyKey, OperationLeaseExpiresAt,
    OperationOwnerId, OperationOwnerLease, OperationOwnershipStatus, OperationStatus,
    OperationStatusSnapshot, OperationSubject, OperationSubmitClockFailure,
    OperationSubmitEventFailure, OperationSubmitStatusFailure, OperatorHint, OpsStatusError,
    OpsStatusRequest, OpsStatusUnavailableSource, OpsWatchError, OpsWatchUnavailableSource,
    ReplayedOperationEvent, ReplicaCount, ReplicaSlot, RetainedArtifact, RevisionId,
    RouteCutoverFailureReason, RouteHostname, RoutePort, RouteTarget, ServiceId, StatusReadFailure,
    WireGuardEbpfComponent,
};
use ployz_core::subjects::OperationApiEndpointExecution;
use ts_rs::{Config, TS};

#[must_use]
pub fn generated_typescript() -> String {
    let config = Config::new().with_large_int("number");
    let mut output = String::from("// Generated by ployz-sdk-types. Do not edit by hand.\n\n");

    output.push_str("export type Brand<T, B extends string> = T & { readonly __brand: B };\n\n");
    output.push_str(
        "export type SafeInteger<B extends string> = Brand<number, `safe_integer:${B}`>;\n\n",
    );
    output.push_str(&format!(
        "export const MAX_OPERATION_EVENT_REPLAY_LIMIT = {MAX_OPERATION_EVENT_REPLAY_LIMIT} as const;\n\n"
    ));

    push_contract_decls(&mut output, &config);
    push_operation_api_contracts(&mut output, &config);

    output
}

macro_rules! exported_types {
    ($macro:ident) => {
        $macro!(
            OperationId,
            OperationOwnerId,
            OperationIdempotencyKey,
            EventSequence,
            ServiceId,
            RevisionId,
            NodeId,
            ContainerId,
            CertId,
            MachineName,
            JoinTokenFingerprint,
            JoinTokenExpiresAt,
            JoinTokenRedeemedAt,
            IssuedJoinToken,
            MachineBootstrapUrl,
            MachineJoinToken,
            ImageReference,
            ReplicaCount,
            ReplicaSlot,
            DeployRequest,
            DeployPlan,
            DeployPlanStep,
            OperationLeaseExpiresAt,
            OperationOwnerLease,
            OperationEventReplayLimit,
            OperationEventReplayRequest,
            OperationEventReplayPage,
            OperationEventReplayCursor,
            ReplayedOperationEvent,
            OperationStatus,
            OperationStatusSnapshot,
            OperationOwnershipStatus,
            OperationSubject,
            MachineAddOperationState,
            MachineAddOperationStateName,
            MachineAddFailure,
            MachineReadinessEvidence,
            MachineReadinessCheck,
            FirstNodeGateway,
            DeployOperationState,
            DeployRunningStage,
            CertOperationState,
            CertRunningStage,
            OperationEvent,
            FailureMessage,
            CancellationReason,
            RouteHostname,
            RoutePort,
            RouteTarget,
            RetainedArtifact,
            HealthCheckFailure,
            WireGuardEbpfComponent,
            ActiveServiceCommitFailure,
            ArtifactUnavailableReason,
            RouteCutoverFailureReason,
            DeployOperationFailure,
            CertOperationFailure,
            OperatorHint,
            CertValidAt,
            CertValidityWindow,
            CertBundleRef,
            AcmeChallengeToken,
            AcmeChallengeValue,
            AcmeChallengeTtlSeconds,
            AcmeHttp01Challenge,
            ActiveCertState,
            ExpectedActiveService,
            ActiveServiceState,
            ActiveServiceCommitRequest,
            DeploySubmitRequest,
            MachineAddRequest,
            MachineAddGateway,
            MachineAddAccepted,
            MachineJoinClusterName,
            InstallArtifactVersion,
            InstallArtifactSource,
            InstallSha256Digest,
            AbsoluteInstallPath,
            MachineJoinBundle,
            MachineJoinPloyzdArtifact,
            MachineJoinRedeemRequest,
            MachineJoinRedeemed,
            MachineJoinRedeemResult,
            MachineJoinRedeemError,
            MachineJoinRedeemUnavailableSource,
            MachineJoinReportRequest,
            MachineJoinReportOutcome,
            MachineJoinReportFailure,
            MachineJoinReported,
            MachineJoinReportError,
            MachineJoinReportUnavailableSource,
            OpsStatusRequest,
            AcceptedOperation,
            OperationApiResponse<AcceptedOperation, DeploySubmitError>,
            DeploySubmitError,
            DeploySubmitUnavailableSource,
            OperationSubmitStatusFailure,
            OperationSubmitEventFailure,
            OperationSubmitClockFailure,
            MachineAddError,
            MachineAddUnavailableSource,
            BootstrapMaterialFailure,
            OpsStatusError,
            OpsStatusUnavailableSource,
            StatusReadFailure,
            OpsWatchError,
            OpsWatchUnavailableSource,
            EventReplayFailure
        );
    };
}

fn push_contract_decls(output: &mut String, config: &Config) {
    macro_rules! push_all {
        ($($type:ty),+ $(,)?) => {
            $(push_decl::<$type>(output, config);)+
        };
    }

    exported_types!(push_all);
}

fn push_decl<T: TS>(output: &mut String, config: &Config) {
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output.push_str("\n\n");
}

fn push_operation_api_contracts(output: &mut String, config: &Config) {
    macro_rules! push_aliases {
        ($($contract:ty),+ $(,)?) => {
            $(push_operation_api_aliases_for::<$contract>(output, config);)+
        };
    }
    crate::operation_api_contracts!(push_aliases);

    output.push_str("export const OPERATION_API_CONTRACTS = [\n");
    macro_rules! push_rows {
        ($($contract:ty),+ $(,)?) => {
            $(push_operation_api_contract_row_for::<$contract>(output, config);)+
        };
    }
    crate::operation_api_contracts!(push_rows);
    output.push_str("] as const;\n");
}

fn push_operation_api_aliases_for<C>(output: &mut String, config: &Config)
where
    C: OperationApiContract,
    C::Request: TS,
    C::Success: TS,
    C::Error: TS,
{
    if let Some(alias) = C::REQUEST_ALIAS {
        output.push_str(&format!(
            "export type {} = {};\n\n",
            alias,
            C::Request::name(config)
        ));
    }
    output.push_str(&format!(
        "export type {} = OperationApiResponse<{}, {}>;\n\n",
        C::RESPONSE_ALIAS,
        C::Success::name(config),
        C::Error::name(config)
    ));
}

fn push_operation_api_contract_row_for<C>(output: &mut String, config: &Config)
where
    C: OperationApiContract,
    C::Request: TS,
    C::Success: TS,
    C::Error: TS,
{
    output.push_str(&format!(
        "  {{ name: \"{}\", subject: \"{}\", execution: \"{}\", request: \"{}\", success: \"{}\", error: \"{}\", response: \"{}\" }},\n",
        C::ENDPOINT.name(),
        C::ENDPOINT.subject(),
        operation_api_execution_name(C::ENDPOINT.execution()),
        operation_api_request_name_for::<C>(config),
        C::Success::name(config),
        C::Error::name(config),
        C::RESPONSE_ALIAS,
    ));
}

fn operation_api_request_name_for<C>(config: &Config) -> String
where
    C: OperationApiContract,
    C::Request: TS,
{
    C::REQUEST_ALIAS.map_or_else(|| C::Request::name(config), str::to_owned)
}

const fn operation_api_execution_name(execution: OperationApiEndpointExecution) -> &'static str {
    match execution {
        OperationApiEndpointExecution::AcceptsOperation => "accepts_operation",
        OperationApiEndpointExecution::MutatesOperation => "mutates_operation",
        OperationApiEndpointExecution::Query => "query",
    }
}
