//! TypeScript contract export owned by the Rust SDK type crate.

use crate::{
    AcceptedOperation, AcmeChallengeToken, AcmeChallengeTtlSeconds, AcmeChallengeValue,
    AcmeHttp01Challenge, ActiveCertState, ActiveServiceCommitFailure, ActiveServiceCommitRequest,
    ActiveServiceState, ArtifactUnavailableReason, CancellationReason, CertBundleRef, CertId,
    CertOperationFailure, CertOperationState, CertRunningStage, CertValidAt, CertValidityWindow,
    ContainerId, DeployOperationFailure, DeployOperationState, DeployPlan, DeployPlanStep,
    DeployRequest, DeployRunningStage, DeploySubmitClockFailure, DeploySubmitError,
    DeploySubmitEventFailure, DeploySubmitRequest, DeploySubmitStatusFailure,
    DeploySubmitUnavailableSource, EventReplayFailure, EventSequence, ExpectedActiveService,
    FailureMessage, HealthCheckFailure, ImageReference, MAX_OPERATION_EVENT_REPLAY_LIMIT, NodeId,
    OperationApiResponse, OperationEvent, OperationEventReplayCursor, OperationEventReplayLimit,
    OperationEventReplayPage, OperationEventReplayRequest, OperationId, OperationIdempotencyKey,
    OperationLeaseExpiresAt, OperationOwnerId, OperationOwnerLease, OperationOwnershipStatus,
    OperationStatus, OperationStatusSnapshot, OperationSubject, OperatorHint, OpsStatusError,
    OpsStatusRequest, OpsStatusUnavailableSource, OpsWatchError, OpsWatchUnavailableSource,
    ReplayedOperationEvent, ReplicaCount, ReplicaSlot, RetainedArtifact, RevisionId,
    RouteCutoverFailureReason, RouteHostname, RoutePort, RouteTarget, ServiceId, StatusReadFailure,
};
use ts_rs::{Config, TS};

#[must_use]
pub fn generated_typescript() -> String {
    let config = Config::new().with_large_int("number");
    let mut output = String::from("// Generated by ployz-sdk-types. Do not edit by hand.\n\n");

    output.push_str("export type Brand<T, B extends string> = T & { readonly __brand: B };\n\n");
    output.push_str(
        "export type SafeInteger<B extends string> = Brand<number, `safe_integer:${B}`>;\n\n",
    );
    output.push_str(&format!(
        "export const MAX_OPERATION_EVENT_REPLAY_LIMIT = {MAX_OPERATION_EVENT_REPLAY_LIMIT} as const;\n\n"
    ));

    push_contract_decls(&mut output, &config);

    output.push_str(
        "export type DeploySubmitResponse = OperationApiResponse<AcceptedOperation, DeploySubmitError>;\n\n",
    );
    output.push_str(
        "export type OpsStatusResponse = OperationApiResponse<OperationStatusSnapshot, OpsStatusError>;\n\n",
    );
    output.push_str("export type OpsWatchRequest = OperationEventReplayRequest;\n\n");
    output.push_str(
        "export type OpsWatchResponse = OperationApiResponse<OperationEventReplayPage, OpsWatchError>;\n",
    );

    output
}

macro_rules! exported_types {
    ($macro:ident) => {
        $macro!(
            OperationId,
            OperationOwnerId,
            OperationIdempotencyKey,
            EventSequence,
            ServiceId,
            RevisionId,
            NodeId,
            ContainerId,
            CertId,
            ImageReference,
            ReplicaCount,
            ReplicaSlot,
            DeployRequest,
            DeployPlan,
            DeployPlanStep,
            OperationLeaseExpiresAt,
            OperationOwnerLease,
            OperationEventReplayLimit,
            OperationEventReplayRequest,
            OperationEventReplayPage,
            OperationEventReplayCursor,
            ReplayedOperationEvent,
            OperationStatus,
            OperationStatusSnapshot,
            OperationOwnershipStatus,
            OperationSubject,
            DeployOperationState,
            DeployRunningStage,
            CertOperationState,
            CertRunningStage,
            OperationEvent,
            FailureMessage,
            CancellationReason,
            RouteHostname,
            RoutePort,
            RouteTarget,
            RetainedArtifact,
            HealthCheckFailure,
            ActiveServiceCommitFailure,
            ArtifactUnavailableReason,
            RouteCutoverFailureReason,
            DeployOperationFailure,
            CertOperationFailure,
            OperatorHint,
            CertValidAt,
            CertValidityWindow,
            CertBundleRef,
            AcmeChallengeToken,
            AcmeChallengeValue,
            AcmeChallengeTtlSeconds,
            AcmeHttp01Challenge,
            ActiveCertState,
            ExpectedActiveService,
            ActiveServiceState,
            ActiveServiceCommitRequest,
            DeploySubmitRequest,
            OpsStatusRequest,
            AcceptedOperation,
            OperationApiResponse<AcceptedOperation, DeploySubmitError>,
            DeploySubmitError,
            DeploySubmitUnavailableSource,
            DeploySubmitStatusFailure,
            DeploySubmitEventFailure,
            DeploySubmitClockFailure,
            OpsStatusError,
            OpsStatusUnavailableSource,
            StatusReadFailure,
            OpsWatchError,
            OpsWatchUnavailableSource,
            EventReplayFailure
        );
    };
}

fn push_contract_decls(output: &mut String, config: &Config) {
    macro_rules! push_all {
        ($($type:ty),+ $(,)?) => {
            $(push_decl::<$type>(output, config);)+
        };
    }

    exported_types!(push_all);
}

fn push_decl<T: TS>(output: &mut String, config: &Config) {
    output.push_str("export ");
    output.push_str(&T::decl(config));
    output.push_str("\n\n");
}
