name: Build eBPF sidecar image

on:
  push:
    branches: [main]
    paths:
      - "ebpf/**"
      - "ebpf-common/**"
      - "ebpf-ctl/**"
  workflow_dispatch:

env:
  IMAGE: ghcr.io/getployz/ployz-ebpf

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: blacksmith-32vcpu-ubuntu-2204
            platform: linux/amd64
            suffix: amd64
          - runner: blacksmith-32vcpu-ubuntu-2204-arm
            platform: linux/arm64
            suffix: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: useblacksmith/build-push-action@v2
        with:
          context: .
          file: ebpf-ctl/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}-${{ matrix.suffix }}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ${{ env.IMAGE }}:latest \
            ${{ env.IMAGE }}:${{ github.sha }}-amd64 \
            ${{ env.IMAGE }}:${{ github.sha }}-arm64
          docker manifest push ${{ env.IMAGE }}:latest

          docker manifest create ${{ env.IMAGE }}:${{ github.sha }} \
            ${{ env.IMAGE }}:${{ github.sha }}-amd64 \
            ${{ env.IMAGE }}:${{ github.sha }}-arm64
          docker manifest push ${{ env.IMAGE }}:${{ github.sha }}